---
title: "#OsakaR で2回目のもくもく会を開催しました"
author: ~
date: '2020-11-02'
slug: osakar-mokumoku-2
categories: [Tech]
tags: [R]
---

[2020/10/31](https://osaka-r.connpass.com/event/193706/)に開催しました。
第1回は[2020/6/6](https://osaka-r.connpass.com/event/178136/)だったので、実に4ヶ月ぶり。
もう少し頻度をあげたいとろですが、家族や他の勉強会とのバランスを考えると中々難しいところです。
今回は私がRStudio PBCのテーブルコンテストに参戦したく、追い込みをかけるために突如企画した、というのが内情だったりします。
昨日の[記事](https://blog.atusy.net/2020/11/01/rstudio-table-contest/)にした通り、無事投稿しました。

せっかくなので徒然と記録や思いを残しておきます。

基本的な流れは

- 14:00--14:15: 自己紹介+お題の宣言
- 14:15--16:30: もくもく (2時間15分くらい)
- 16:30--17:15: 成果報告
- 17:15--18:00: 休憩
- 18:00--20:10: 懇親会

といった感じでした。

参加者は6名で、それぞれのお題は以下の通り。

- RStudioのテーブルコンテスト by atusy[\@Atsushi776](https://twitter.com/Atsushi776)
- さけのわデータ可視化 by 茶畑[\@soupcurry049](https://twitter.com/soupcurry049)さん
- 日本のソムリエ資格保有者の男女比の可視化 by Yuta Kanzawa[\@yutakanzawa](https://twitter.com/yutakanzawa)さん
- データベース運用のRによる効率化 by _[\@SugiAki](https://twitter.com/_SugiAki)さん
- 日本Pandocユーザ会の行動規範制定 by 藤原惟[\@skyy_writing](https://twitter.com/skyy_writing)さん
- 多次元ガウス分布の学習と予測 by しょこβ[\@anemptyarchive](https://twitter.com/anemptyarchive)さん

藤原惟さん以外はいつも朝もくにも参加してくれている面々ですね。
皆さんのおかげでモチベーションを維持できている側面があるので、本当にありがたい限りです。
藤原惟さんはイベント概要に

> Rユーザーの集まりなので、基本はR関係のことをしていますが、PythonやLuaなど他の言語を触ってもOK。

と記しておいたのが功を奏して参加して頂けたようです。

この人数でも成果報告に40分かかったので、今後開催する時は人数を10人に制限するかな……？
門戸を広げたい思いと、まったりやりたい思いとがあって悩ましいところ。
人数が増えると成果報告に時間制限を設けざるをえなくなります。
口頭での成果報告は「成果を出すぞ！」というモチベーションになるので維持したいです。
纏まった成果を出す必要はないですが、制限時間内に何かしら形にできる粒度に課題を設定するスキルを磨きたい思いもあります。

成果報告時には、ooしたいならxxって手があるよ、みたいなアドバイスが行き交いました。
いいことですね。
一方で、作業中に交流できていれば、もっとよかったのではとも。
SkypeやMeetを繋いでいても作業中はだいたいみんな無口になっちゃうので難しいですね。
今回は作業中はMeetを切ってSlackにしたので余計かもしれません。
もっと試行錯誤の過程を私から共有し出せば、そういう空気を作れたかも？
気付いた頃には16時を過ぎて成果が出だしてましたね。
一応それからでもSlackに状況を投稿すると、呼応して投稿してくれる人もいました。

懇親会では実に様々な話をしました。

- イベントに関するあれこれ
- 好きな地域の魅力
- プログラミング言語の比較
- 仕事のこと
- 家庭のこと

他にも色々あった気がする……。

もくもくしてると、これ、そのままどこかの勉強会で発表できるんちゃう？
みたいな話になりますね。
近いところだと12月のJapan.R。
私はもくもくネタに限らずネタを持ってますが、冒頭でも記した通り、私生活とのバランスなんかもあって見送り濃厚……。

長く続いている勉強会はなんとなく登壇への敷居が高く見えるそうで、
Japan.Rのように「発表初心者向け5分枠 x 5名」みたいなのを設けるの大事なんだろうなあという話もしました。
一方で発表してみたいがどんなネタを持ち込めば良いかわからない、みたいな人もいそうです。
そんな人向けにお題ありきのLT枠も良いかも、なんて話もしました。

- 好きなパッケージの概要や特定の機能の紹介
- 失敗談・試行錯誤していること

とか。

今のところOsaka.Rでは勉強会を開催していませんが、
お題ありのLT大会にして他のRコミュニティとの差別化を図っても面白そうです。

仕事については、データ分析・機械学習関係の求人は関東を出るとほとんどPythonだよねという話がありました。
私が大阪・京都で転職活動した時は、Rをチーム単位で使ってる求人はなかったかな。
「PythonまたはRの経験」とある求人は大体Pythonです。
素養のある人を広く募るためにRも入っているようですね。
一方でチームとしては言語を統一したい、サービス化・納品する時にPythonの方が都合がいいといった事情があるようです。
たまたま、場にRに限らずPythonやJulia、Rubyなど、様々な言語を触っている人ばかりが集っていたこともあり、
「色々やっておいた方がいいよね。あくまで手段なんだから」という身も蓋もない答えになってしまいました。

あとはプライベートなことも入ってくるので、この程度にしておきますか。
長く書いてしまいました。

Enjoy!!