---
title: Osaka.Rを立ち上げて、リモート朝モクやってます
author: ~
date: '2020-04-21'
slug: osakar-asamoku
categories: [Tech]
tags: [OsakaR]
output:
  blogdown::html_page:
    toc: true
---

# Osaka.R始めました

転職して大阪に引越したのを機にOsaka.Rを始めることにしました。
奇しくもOsaka.Rを始めたいと同時期に思っていたくろきちさん、わさびさんと
共に立ち上げることにしました。

地域に根差すRコミュニティとしては、
Tokyo.Rを筆頭に、Sendai.R、Tsukuba.R、Okayama.R、Fukuoka.R、Okinawa.Rなどがあります。
多くは勉強会を運営しています。
関西にはかつて旧Osaka.RやKobe.Rが立ち上がりましたが、
発表者集めなどの大変さで消えていきました。

旧Osaka.Rの代表から名前を引き継いだのはいいものの、
しんどいのでまた消えるでは悲し過ぎます。
そこで我々は継続しやすい運営を心掛けることにしました。
運営3人だけでもできる「もくもく会」から始め、
集り具合を見ながら勉強会開催を考えればいいかなという結論になりました。
「もくもく会」ではその日何をやるのか宣言してもらい、
最後に軽く何をしたか共有してもらうつもりでした。

# 外出自粛の中でできること = リモート朝もく

もくもくしようと話しがまとまったのが2月で
初回を3月に見据えていましたが、
コロナウィルスの蔓延により立ち消えになりました。
4月も狙いましたが状況は改善せず、GW明けかなと話していたら緊急事態宣言が発令されました。
ままならないです。

Tokyo.RがリモートLT大会を行ったように、
我々もリモートで何かやりたいと話し合いました。
いつか来るオフランインOsaka.Rに向けて存在感を示しておきたいのです。

そこで、リモートワークの導入により、
通勤に充てていた時間を朝もくに使おうと決めました。
私の朝起きが遅くなっていた原因の排除をOsaka.Rに求めたとも言います。
詳しくは[こちら](https://osaka-r.connpass.com/)。

リモート勉強会の開催についても話し合いました。
しかしTokyo.Rが既に開催しており、
Osaka.Rでもやったところで発表者・視聴者の取り合いになって
幸せになる人はいないかなと判断しました。
Tokyo.Rのリモート勉強会にせよ、Osaka.Rのリモート朝もくにせよ、
オンライン開催の性質上、地域の垣根は完全に排除されています。
だったらひとまず勉強会はTokyo.Rだけでいいかなと。
Tokyo.Rの勉強会の内容は自由なので、
RStanやShinyなど特定のトピックに絞った勉強会なら開催する価値もありそうです。
しかし、内容が自由で世界中どこからでも発信できる状況にあってすら、
Tokyo.RのLT発表枠が埋まらなかったのを見ると、
ぽっと出が継続していくのは大変そうだなあと思います。

## 朝もくの感想

以下のメリットがあります。

* 朝、ちゃんと起きられる
* 毎日、こつこつと何かを進められる
* 人の関心事項に触れられる
* 困ったことがあれば人に聞ける

参加者には何に取り組むか可能な範囲で宣言してもらっています。
人々の関心がどこにあるか見えるのは面白いですね。
かぶっている人同士で勉強会が立ち上がる未来もあるかなと思ってます。
というか、私がそうしたいのですが、
目下もくもくしている課題を解決するまではお預けかな。
まだ当分かかりそうです。

ちなみに私はサボらないように、作業風景を画面共有しています。
私の作業風景をもくもくと眺めたい人は多分いないと思いますが……。

# 個人的なOsaka.Rを立ち上げの背景

Tokyo.Rに何度か参加して楽しかったので、運営もしてみたいが、如何せん遠い。
なら近場に作ればいい。
割とそんな軽いノリが占めています。

もちろん、近隣のRユーザーたちとコミュニティを形成し、
仲良くなりたい、協力し合いたいという思いもあります。
京阪神で転職活動をしたときに、Rのお仕事は限られているなという印象を持ちました。
Twitterでも関東や九州からはお声がけ頂けましたが、関西でRの話はとんとなかった次第です。
ただ、これは、事業として大々的にRを使っているところが少ないだけで、
社内でひっそりRを使っている方はそれなりの数いるだろうと思っています。
あるいは大学の研究室で使っているが、情報交換の場は研究室内に滞っている、交換する相手がいない、なんて方々もいるでしょう。
Osaka.Rをきっかけにそんな人たちが集るといいな。
