---
title: Osaka.Rで昼間のリモートもくもく会を開催しました (2020/6/6)
author: ~
date: '2020-06-08'
slug: osakar-mokumoku-20200606
categories: [Tech]
tags: [R, Osaka.R]
---

Osaka.Rで昼間のリモートもくもく会を開催しました。
これは毎平日の朝に行っているリモートもくもく会のグレードアップ版的な位置付けです。
休日開催することで、朝もくより長く時間をとり、進捗を出しつつさらに参加者同士で進捗を可視化しようという試みです。

当日の流れとしては2時から自己紹介しつつ作業を開始し、5時半から6時の間に進捗を共有するというもの。
運営2名と一般5名の合計7名の参加者でもくもくしました。
みなさん、3時間半とは思えないほどの進捗を[出していて、驚きました。
7名中3名も、自然言語処理をテーマにされていたので、自然言語人気やなあと思いました。

終わったら1時間の休憩を挟み、19時から2時間の懇親会を開催しました。
最初に触れた言語は何だったとか、子育て大変だとか、色々な話題で盛り上がれました。

もくもく会としてはこれくらいの規模のほうが、全体を把握しやすくていいかも知れませんね。
つい50人を上限に募集を募りましたが、終わってみればこれでよかったように思います。
remo.coというチャットサービスを使えば、6人ごとに席を分けられるので、大人数でもいけるかもしれません。
ただ、無料試用では2時間が上限だったので、採用を見送りました（前日に気付きました）。

7人でも、内容が伝わるように進捗を共有すると30分を使ってしまうので、50人もいたらhogehogeしました！しか言えなくなりそうにも思います。
それだと自己紹介のときにhogehogeします！宣言したのと変わらなくなってしまうので、やはり少人数向きなのかなあ。

今後Osaka.Rでもくもくしていくにしろ、他のイベントを開催するにしろ、参考になる会でした。

# みなさんの成果

Twitterの #OsakaR で見付けられた範囲でまとめておきます。

## Atusy

```{=html}
<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="ja" dir="ltr">みなさん、3時間半のもくもくで驚くほどの進捗!<br>私はRでライフゲーム実装してました。これはダイハード。<a href="https://twitter.com/hashtag/OsakaR?src=hash&amp;ref_src=twsrc%5Etfw">#OsakaR</a> <a href="https://t.co/Lu8z1XUk6w">pic.twitter.com/Lu8z1XUk6w</a></p>&mdash; atusy (@Atsushi776) <a href="https://twitter.com/Atsushi776/status/1269195322871279616?ref_src=twsrc%5Etfw">June 6, 2020</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```

## Kanzawaさん

```{=html}
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr"><a href="https://twitter.com/hashtag/OsakaR?src=hash&amp;ref_src=twsrc%5Etfw">#OsakaR</a> の懇親会の食糧が届くのを待つ間にさっきは雑だったプロットを清書しました。左下の角を赤いL字で囲ったメッシュがAMEDAS観測所のあるメッシュです。右下のグレーの領域（東京湾）に近い（東経139.8度付近）2つは羽田と新木場で、それらから見て北西方向（北緯35.7度付近）にあるのが気象庁。 <a href="https://t.co/mi76ILvA5e">pic.twitter.com/mi76ILvA5e</a></p>&mdash; Yuta Kanzawa (@yutakanzawa) <a href="https://twitter.com/yutakanzawa/status/1269206989042638848?ref_src=twsrc%5Etfw">June 6, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
```
## usagisan2020さん

```{=html}
https://www.slideshare.net/otanet/osakar-20200606-1418
```

> 自動要約、自動文書要約のはしりを、簡単にまとめてみました。
Rでもできるので、Osaka.Rのもくもく会で行った成果物です。https://osaka-r.connpass.com/event/178136/　
・自動文書要約は、やはり主観評価だと思います。
>
> 評価指標はあるものの、文書の長さと各人の目的により、満足度となる効用は異なると考えられるのではないかと。。。
>
> Rで簡易的に、いくつかの異なる手法で、比較考察できるのはメリットだと思われます。
なので、あまり深入りしても、あのー、そのー的な(すみません)


## Wasabiさん

```{=html}
<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="ja" dir="ltr">みなさん、3時間半のもくもくで驚くほどの進捗!<br>私はRでライフゲーム実装してました。これはダイハード。<a href="https://twitter.com/hashtag/OsakaR?src=hash&amp;ref_src=twsrc%5Etfw">#OsakaR</a> <a href="https://t.co/Lu8z1XUk6w">pic.twitter.com/Lu8z1XUk6w</a></p>&mdash; atusy (@Atsushi776) <a href="https://twitter.com/Atsushi776/status/1269195322871279616?ref_src=twsrc%5Etfw">June 6, 2020</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```