---
title: RStudio PBCのテーブルコンテストに投稿しました
author: ~
date: '2020-11-01'
slug: rstudio-table-contest
categories: [R]
tags: [ftExtra]
---

2019年のShinyコンテストに続き、2020年は表コンテストが開催されました（[開催案内](https://blog.rstudio.com/2020/09/15/announcing-the-2020-rstudio-table-contest/)）。
実用的なのからネタなものまで幅広くテーブルを募るもので、投稿期間は9/15から10/31でした。
大枠としては、

1. **Single Table Example**: 面白い構造をした表、便利な機能や特殊な機能を使った表、特定の分野で用いられる表など
2. **Tutorial**: パッケージの機能紹介を通して素敵な表を組む方法をまとめる
3. **Other**

で、更に表の形式として

- 静的なHTML
- 動的なHTML (JavaScriptを使ったもの)
- 印刷物
- shiny

という分類もあり、組み合わせれば12通りの枠があります。

私は**ftExtra**パッケージの宣伝を兼ねて、vignetteを**Tutorial**の**静的なHTML**枠で投稿しました。
**ftExtra**パッケージの最大のウリは、**flextable**パッケージで表を組む時にマークダウンを利用可能にするものです。
しかし、マークダウン記法のサポート範囲に不満があったので、機能強化から始めました。
間に合うか冷や冷やしましたが、10/31にOsaka.Rとしてもくもく会を開催することで、追い込みをかけました。

投稿すると↓のように、RStudio Communityへの投稿という扱いになるようです。

> https://community.rstudio.com/t/format-columns-as-markdown-with-the-flextable-and-ftextra-packages-table-contest-submission/86497

掲示板形式で他のユーザーからの反応が貰えるのが嬉しいですね。
私はShinyコンテストの受賞者から賞賛を受けてめっちゃテンションがあがってます。
もっとLikeが増えると嬉しいな！

コンテストの結果がいつ出るかは不明。
開催案内によると景品は以下の通り。

- 優秀賞
    - shinyapps.ioのベーシックプランまたはRStudio.Cloud Premiumを1年無料で利用する権利
    - RStudioのグッズ$200分。Tシャツ、書籍、マグが選べるもののアメリカ国内限定らしい
- 佳作
    - RStudioのパッケージと、表作りに便利なパッケージのhex stickerなど

優秀賞の景品は持て余すものや、もらえないものがあるので、佳作をとれると嬉しいなあ（笑）

> 表作りに便利なパッケージ

とはおそらく、**DT**、**gt**、**reactable**、**flextable**、**huxtable**のこと。
これらのパッケージの作者は本コンテストの審査員をしているそうです。
