---
title: "vim-jp ラジオ #41聞いた - モバイルDevOpsエンニジアのgiginetさん登場！"
author: atusy
date: '2025-05-21'
slug: 
categories: [Tech]
tags: [vim-jp radio]
output:
  blogdown::html_page:
    md_extensions: +east_asian_line_breaks+task_lists
highlightjs: []
summary: |
---

最近ちっともvim-jp ラジオをきけてなかった。

特段理由らしい理由はないのだけれど、強いていうならYAMORIのビートボックスがよすぎてYoutubeあさったり、TENDREのライブに行ったり、耳は音楽を聴くのに忙しかったのかも。

<iframe width="560" height="315" src="https://www.youtube.com/embed/pUak4njRARA?si=VZK-qPTTwaTduhpH" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

vim-jp ラジオは感想を書く訓練にも使わせてもらってたのもあって、一度途切れてしまうと、どんどんたまってなんとなく億劫になっていたのもありそうだ。

直近のやつとりあえず聴きゃいいのにね。
最後に感想書いたのは2025-01-28らしい。めっちゃ前やん。

> [vim-jpラジオ#27・#28聞いた - 実はEmacs30年選手！t-wadaさん登場！](https://blog.atusy.net/2025/01/28/vim-jp-radio-27/)

というわけで、直近だとgiginetさんの回が#41, #42と続いていたので、2つを聴いて感想を書こうと思った。
ただ、思った異常に#41が濃かったので、#42は次回に回す。

> 【モバイルDevOpsエンニジアのgiginetさん登場！】エンジニアの楽園 vim-jp ラジオ #41 \
> <https://audee.jp/voice/show/103948>

giginetさんはありすえさんの後輩とのことだけど、年に由来する上下関係を感じさせなくて、互いにリスペクトしてる感がとてもよかった。

2人は大学のサークル繋がりらしい。
競プロしたり、ゲーム作ったり、オンプレでサークルのウェブページを運用したり、エンジニアとしたインターンシップやバイトをしたり、大学時代から着々とスキルを高めてた感がある。

こういう話を聞くと、何を始めるにも遅すぎることなんてないと言うものの、早々に青春を捧げられるようなナニカを見つけられるって強みだよなと思う。
いや、ありすえさん、ちゃらかったらしいし、別に捧げてまではいなかったかもだけどね。

更に仲間もいるとか最強じゃん。
学生時代のatusyはどちらかというと、1人もくもくとやっていたタイプだったし、プログラミングとの出会いは修士載ときだったので、ちょっと羨ましい。

giginetさんがモバイルDevOpsエンジニアになる過程で時流にうまく乗ったって話があったけど、giginetさんの戦略性のた高さだけじゃなくて、興味領域に早いうちから取り組みつつコミュニティを大事にしてきた成果なんじゃないかなーと思った。

あれだな、つい誰かをプログラミングつよつよ！って抽象化しちゃうと一点突破の人のように見えちゃうんだけど、実際は色んな強みが絡み合ってるんだなーと、あたりまえのことを再認識させてくれる良いラジオだった。

**ENJOY**




<!--

ありすえさん後輩特集。
モバイルDevOpsエンジニアgiginetさん。

tomoyaさんが知らないありすえさんの知人は初。

モバイルエンジニアになるまで。

くされえん。15年くらい。
大学のサークルでちゃらい人だったありすえさん。
二人ともはてなでインターン経験。
giginetさんは夏休みの間京都でバイトした。
それ聞いてありすえさんも参加。

数少ないエンジニア向けインターンで旅費滞在費つきだった。

giginetさんはcookbadに2015年から。2022年に転職してLINE。
新卒の1年を覗いてモバイル開発に。
toCはモバイルから作るのがあたりまえみたいなタイミングで波にのれた。

出会いはプログラミングサークル。競プロ。
1人が入力してる間に2人が紙に書くとか。

途中でフリーゲームを作るコミュニティに移動。

tomoyaさんも地方→東京。

バンドとかって地方から東京でてくるケースあるけど…… 一発あてるときって
地方で出会った人たち

- 偶然、才能がある人たちが地方にあらわれた？
- 集った人たちが影響しあった結果成功した？

どっちがあてはまるんだろ？
tomoyaさんのテーマ。

ありすえさんやgiginetさんはどう思ってる？

alisue: どっちも？
giginet: コミュニティあったのはでかいよね。みんなすごいからモチベあがる

tomoya: alisue/gigignetともに執筆経験あるの異常。コミュニティに価値はある。突出してすごいのがいた？

alisue: ぼく？でもみんな尖ってるところが違ってた

サークルがチーム開発のきっかけ。サブバージョンとかGitとか導入した。
余ったPCでオンプレ運用。
アプリケーションサーバーも。
ドメインは買ってた。

giginetさんはCLIやVimをちっくんに教えてもらった。
他はもともとVim使い。

初期のはてなも少数の詳しい人から発展。

コミュニケーションはSkype
SkypeかIRCしかなかった。

giginet2014年に1冊目目350ページ。重かった。
エンジニアチームの生産性の高めかた。シニアによるオムニバス。
業務経験をベースに。

tomoyaさんは単著3本。

モバイルエンジニアとモバイルDevOpsエンジニアって？

- 事業に近いアプリケーションレイヤー画面を作ったりするひと
- 開発ツール・ログ基盤・認証……

CookPadにいたときからそう。

開発基盤チームがあるのって大きい組織だけだよね。
なので、その背景から説明する章だった。

最近はSREのほうがはやってるからごちゃごちゃしがち。

開発基盤ってなにしてる？
LINEっていろんな機能がついてるからビルドに時間がかかる。
イテレーションをどう早くするか。
依存関係のビルドをCIでキャッシュしとく。
ビルド単位を小さくするとかリファクタリングするとか。

LINE規模になるとツール導入だけでぽんとはいかない。
でかいところでしかわからない知見ってあるよね。

Cookpadはじょじょにでかくなった。LINEはすでにでかかった。
ギャップはあった？
前者の方が小さくて進めやすかった。LINEはCookpadでできてたことを再生産すればよかった。あと大きい組織でそれをやる

-->
