---
title: "ふりかえり手法として「力」に注目する"
author: atusy
date: '2025-09-03'
slug: retrospective-method-strengthen
categories: [Tech]
tags: [Neovim, LSP]
output:
  blogdown::html_page:
    md_extensions: +east_asian_line_breaks+task_lists
highlighhtjs: [Lua]
summary: |

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = "#>", collapse = TRUE)
set.seed(123)
options(digits.secs = 0)
```

私生活から仕事まで、私たちはさまざまな場面で「ふりかえり」を行います。
「ふりかえり」を通じてより良い未来を目指します。

この「未来」は
ふりかえりを通じて、私たちは様々な形で「力」を得ます。

たとえばできたこと・できなかったことも、どうしたいかによって様々な「力」を得ればいいと判断できます。

* できたこと
    * 再現可能にする力
    * 効力を高める力
    * 実現速度を上げる力
* できなかったこと
    * 再発を防止する力
    * 影響を最小化する力
    * 早期発見する力
    * 影響発生を遅らせる力

KPT（Keep, Problem, Try）にしてもYWT（やった、わかった、つぎやる）にしても、本当に重要なのは「力」を得ることです。
「力」の所属が個人か組織かは問いません。

しかし、定番手法には以下のような課題を感じていました。

* 共通
    * よくある手法は議題の洗い出しに優れる一方で、どんな「力」を得るか方向性を探るには参加者の力量を問う
    * よかったことってなんだろう？悪かったことってなんだろう？と思い起こすのが難しい
        * ふりかえりを始めたばかりだとなにを言えばいいかわからず、継続して成熟するとあえて言うことがなくなる（と錯覚する）
    * 課題が明らかなら、わざわざKPTやYWTを使うまでもなく、課題を分析してアクションアイテムを決めればいい
    * 事実のふりかえりになりがちで、人や組織に対する褒めや感謝が出にくい
* KPT
    * PのProblemを「悪い問題」ととらえがちで、挑戦を含む「解決すべき課題」として扱いにくい
* YWT
    * TのやったことやWのわかったことからTを導く技術が必要
        * ベースとしてやってないことや、わかってないことと、TとWに記載されないことを把握する必要がある


そこで、ふりかえりの手法として「力」に注目することを提案します。


「ポジティブふりかえりマッピング」

* ふりかえりはポジティブに… <https://www.insurtechlab.net/positive_retro/>
