---
title: "目標達成のためにこそKPTのKeep（続けたいこと）を大事にふりかえりたい"
author: atusy
date: '2025-11-21'
slug: keep-keep-in-your-mind
categories: [Essay]
tags: [KPT, Retrospective]
output:
  blogdown::html_page:
    md_extensions: +east_asian_line_breaks+task_lists
---

ふりかえりでは目につく課題が取り沙汰されがちだ。

だからというとひねくれているが、私は成功体験に意識を向けることを大事にしている。

> 言語化され成功体験は再現性を生み出し、更によい成功を生むエナジーなのです \
> by [[アジャイルジャパン2025]あなたのアジャイルがうまくいかない10の理由～"Reboot"のための処方箋～](https://www.docswell.com/s/samuraiRed/5WMQYG-2025-11-13-205802)

そうそうこれが言いたかったんだよおお、と思ったので、改めて自分の思うところをまとめておこうと思う。

成功体験が更によい成功を生むなら、その先には目標達成が待っている。
「我々はなぜここにいるのか」を体現してくれる。
そこへ至るエナジーはあればあるほど良い。

だから成功体験が大事なのだ。

じゃあどう大事にしようかということで、KPTを題材に考えてみる。

KPTはKeep（続けたいこと）、Problem（課題）に対してTry（改善案）を考えるフレームワークだ。

Problem（課題）は「治したい」にせよ「伸ばしたい」にせよ、変化を指向する。Tryを考えやすい。

おかげで、チームとして取り決めての解決が必要なことか、深く考えずに飛び付きたくなる。
我々は問題だらけだとか、ろくな成功がないだとか、そんな気分になってしまう。

だから、深く考える前にKeep（続けたいこと）に目を向けたい。

* ただ今まで通り続けばいいのか？
* そもそも再現可能か？
* 伸びしろはあるか？

前向きな話なのはエナジーになるし、これらの問い掛けはKeep発のTryの種にもなる。

KeepとProblem、どちらにTryしていくか考えるのはそれからで丁度いい。
場を温めておこう。

そうそう、Keep（続けたいこと）を深堀るには発掘も欠かせまい。
ここらはファシリテーターに限らず慣れてる人の腕の見せ所だ。

* しょうもない成功も拾い上げて、ハードルをさげる
* Problem（課題）まみれになったらその周辺に成功がなかったか話をふる
    * 課題発見能力の高さや、初動の速さなど、さまざまなKeep（続けたいこと）要素があるはずだ
* KeepかProblemか迷うくらいならKeepに書くよう促す

課題発見に能力がいるように、成功発見も能力がいる。伸ばせる。伸ばそう。

課題解決は、しばしば「どうありたいか」より「どうしたくないか」に引きずられがちだ。

成功体験の能力を伸ばすと、チームの「どうありたいか」を引き出せる。
更によい成功を生むだけでなく、課題解決の羅針盤にもなる。

そうしてKeep（続けたいこと）にもProblem（課題）にも結果としてバランスよく付き合えるようになれば、途方のない目標達成にも近付く実感を得られると思うのだ。
それも楽しく、ね！

# ENJOY!

KPTは適用できる場面が多く、導入の敷居も低い。
だからって安直に進めるより大事にしたいポイントがいくつもあるので、こんな感じでちょこちょこ言語化していきたい。
