---
title: "自分用コマンドにはプレフィックスつけるとよさげ"
author: atusy
date: '2025-04-24'
slug: prefix-personal-commands
categories: [Shell, Taskfile]
tags: []
output:
  blogdown::html_page:
    md_extensions: +east_asian_line_breaks+task_lists
highlightjs: []
summary: |
    `~/.local/bin/T-hoge`みたいに`T-`とかのprefixつけておくと、補完が効いて便利。
    大文字にしとくと、被りも少ないよ。
---

```{r setup, include=FALSE}
```

タスクランナーの`task`コマンド（<https://taskfile.dev/>）はグローバルタスクを定義できるのがいいところですね。
`~/Taskfile.yaml`に定義しておくと、どのディレクトリからでも実行できるので、便利です。
これを活用したくて、[go-task/task](https://github.com/go-task/task)にコントリビュートして、Fish向けにグローバルタスクの補完を実装しました。

> Taskfile（taskコマンド）のfish補完定義を改善してグローバルタスクに対応した
> <https://blog.atusy.net/2025/04/23/go-task-and-fish-completion/>

しかし、いくつか不安がありました

- タスクランナーはグローバルタスクに対応しているものばかりではないので、`task`コマンドから乗り換えづらい
- 補完定義をFishしか対応させられなかったので、他のシェルで使いづらい

そこへきてvim-jpで

> この手のツール、大体シェルの設定かシェルスクリプトでいいやってなるんだけど

というコメントをもらい、ふと、そういえば自分も`~/.local/bin/`に自分用コマンドを定義しているなと思いました。

個人的には、コマンド名を覚えやすいものを`~/.local/bin/`に配置し、そうでもないものをグローバルタスク化していました。
グローバルタスクは、`task --global`で補完候補を得られるので、名前を記憶する必要がなかったわけです。

ということは、`~/.local/bin/`下に特定のprefixを持つ実行ファイルを置いておけば良いではないかと気付きました。

たとえば、システムを更新するスクリプトは `~/.local/bin/T-system-update` といった具合にしておくと、`T-`でコマンドを補完させればいいわけですね。
`T-`をprefixにしたのは、**task**を連想しやすいからです。

この方法なら`task`コマンド不要ですし、Fish以外のシェルでも容易に補完できます。

やったね！

同じようにローカルタスクも実行ファイルで管理できるといいなーと思ったのですが、気にしないことにしました。
動的に`PATH`を変更する手間を思えばタスクランナーを採用すればいいですし、`task`コマンドに縛られず任意のタスクランナーを使えるので、問題になりません。

**ENJOY**
