baseurl = "/"
relativeurls = true
publishDir = "docs"
hasCJKLanguage = true
languageCode = "ja-jp"
title = "A Hugo website"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Category"
    url = "/categories/"
[[menu.main]]
    name = "Tags"
    url = "/tags/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/atusy"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/Atsushi776"

[params]
    description = "Atusy's blog"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "atusy.jpg"
    width = 50
    height = 50
    alt = "Logo"

