baseurl = "https://blog.atusy.net/"
relativeurls = true
publishDir = "public"
hasCJKLanguage = true
languageCode = "ja-jp"
title = "Atusy's blog"
theme = "hugo-bootstrap"
googleAnalytics = "UA-133202767-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "drafts$", "content/.*\\.ya?ml$"]
defaultContentLanguage = "ja"
buildDrafts = false
buildFuture = true
footnoteReturnLinkContents = "↩"

# Pagination
paginate = 7
paginatePath = "page"

pygmentsUseClasses = true
pygmentsCodeFences = true

[taxonomies]
  # tag = "tags"
  category = "categories"
  tag = "tags"

[languages.ja]
  languageName = "Japanese"

  # Replace the default footer message with a localized message
  # copyright = "Hugo template made with ❤ by Xzya"

  [[languages.ja.menu.main]]
    url = "https://github.com/atusy"
    name = "GitHub"
    weight = 1
  [[languages.ja.menu.main]]
    url = "https://twitter.com/Atsushi776"
    name = "Twitter"
    weight = 2
    
[languages.en]
  languageName = "English"

  # Replace the default footer message with a localized message
  # copyright = "Hugo template made with ❤ by Xzya"

  [[languages.en.menu.main]]
    url = "https://github.com/atusy"
    name = "GitHub"
    weight = 1
  [[languages.en.menu.main]]
    url = "https://twitter.com/Atsushi776"
    name = "Twitter"
    weight = 2

# Links format

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
  # Main sections (currently used for the recent posts in the sidebar)
  mainSections = ["post"]

  # Default author
  author = "Atusy"

  # Date format (default: Jan 2, 2006)
  date_format = "2006-1-2"

  # Display post summaries instead of content in list templates (default: true)
  # truncate = false

  images = ["/images/atusy-large.jpg"]
  
  [params.sidebar]
    # Whether to show the recent posts or not (default: true)
    showRecent = false

    # Whether to show the taxonomies or not (default: true)
    # showTaxonomy = false

    # How many posts to show on the sidebar (Default: 5)
    # num_recent_posts = 5

[related]
 
threshold = 80
 
includeNewer = true
 
toLower = true
 
[[related.indices]]
name = "keywords"
weight = 150
[[related.indices]]
name  = "author"
toLower = true
weight = 30
[[related.indices]]
name  = "tags"
weight = 100
[[related.indices]]
name  = "categories"
weight = 100
[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"
