---
title: "Japan.R 2024で地域コミュニティのOsaka.Rについて発表した"
author: atusy
date: '2024-12-12'
slug: japanr-logging
categories: [R]
tags: []
output:
  blogdown::html_page:
    md_extensions: +east_asian_line_breaks+task_lists
summary: |
  前の発表で力尽きてて、何も考えずに楽しくお話しちゃった回。
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = "#>", collapse = TRUE)
```

2024-12-07に開催されたJapan.R 2024で登壇しました。

登壇内容は以下の2本。

- [Happy Structured Loggin in R（構造化ログ入門.R）](https://atusy.github.io/japanr-2024-logging/)
- [Osaka.Rについて](https://github.com/atusy/japanr-2024-osakar)

ログの発表の感想は既に[記事](https://blog.atusy.net/2024/12/10/japanr-logging/)にしたので、今日はOsaka.Rの発表の感想を書こうと思います。
あとは、全体の振り返りも書きたいですね。

# 内容振り返り

コミュニティの概要と、コミュニティと私の個人的な関係性、実際の活動内容、今後のこと、くらいを1分ちょいずつで話せればいいかなーと思って、Japan.R当日の朝に頑張って用意しました。

5分枠だったこともあり、あっさり目の内容なので、リンク先を見てもらうのが早いと思います。

> <https://github.com/atusy/japanr-2024-osakar>

# 発表の振り返り

5分枠だったのに、つい話すのが楽しくなって6分半話して打ち切りになりました。
大反省。

先のログの発表では時間ぴったりだったのになあ。
たぶん力尽きて頭回ってなかったのだと思います。

Osaka.Rは続けやすいようにゆるくやってますみたいな話をしたのですが、一体何回「ゆるい」って言うんだと思いながら、「ゆるい」を連呼してしまいました。
本当に反省の多い発表……。

ログの話はかなり真面目路線だったので、打って変わって私に親しみを感じてもらえたなら、結果オーライなんだけど、どうだろう……。

コミュニティって続けるのが大変だから、ゆるくても続けるだけで価値があるよということは伝えられたかなと思う。
実際続けられているおかげで、Japan.Rでログの話をしたりするきっかけも生まれたし。

ただ、もう少し伝えたかったこともあって、

- サードプレイスとしてのコミュニティって大事だよ。自分の居心地のいいところ探そう
- 今シーズンはスキーに行きたいと思ってるから、同行して、ついでにR合宿できるといいなーとひっそり思ってる

あたりはまったく触れられませんでした。

あと、他のコミュニティは、オフラインイベントに力を入れてて素敵でした。
それに、どこも懇親会がめっちゃ楽しそう。
私の準備が間に合わず、方々にOKもらうの間に合わなかったのですが、こないだOsaka.Rでお寿司食べにいった時の写真くらい掲載できればよかったですねえ。

# ENJOY!!

またどこかの会場でお会いしましょう！
