---
title: Osaka.Rで朝もくを続けて2年8ヶ月くらいになった
author: ''
date: '2022-12-04'
slug: osakar-asa-moku
categories: [Tech]
tags: [R, Osaka.R]
output:
  blogdown::html_page:
    md_extensions: +east_asian_line_breaks+task_lists
---

本記事は2022/12/04のR言語アドベントカレンダーの記事です。

> https://qiita.com/advent-calendar/2022/rlang

12/03はyutannihilationさんによる「[dplyr 1.1.0からはgroup_by()の代わりに.by引数が使えるらしいという話](https://notchained.hatenablog.com/entry/2022/12/03/000000)」でした。

12/05はpaithiov909さんによる「[宮沢賢治『春と修羅』の季節に関連する語彙の分析](https://lyrikuso.netlify.app/haruto-shura/)」です。


# 本題

Osaka.RはR言語界隈の地方コミュニティの一つです。

朝もくを主な活動として3年近くが経とうとしています。

これを期に活動を振り替えることにしました。

なお、Osaka.Rの詳細やSlack参加方法は以下のリンクから辿れます。
興味を持って頂いた方は是非ご参加ください。

https://osaka-r.connpass.com

## これまでの経緯

Osaka.Rは2020年2月に私が大阪に引っ越して来たのを期に、くろさんとわさびさんと私の3人で立ち上げました。

Tokyo.Rのように勉強会を開催にするには人と場所の継続的な確保が大変だろうとの判断で、「現地開催」のもくもく会をやろうと話していたのを覚えています。

あいにくコロナウィルスの流行が重なり、現地開催は難しくなりましたが、リモートワークで朝の通勤時間を活用するもくもく会をすることにしました。

当初はSkypeを使ってましたが、サービスが不安定だったり、もくもくと作業している中で音声や映像は不要だったりで、いつの間にか活動の場はSlackに移りました。

朝もくは7時半から10時を目安にいつ出入りしても良い形式。
Slackでは月〜金の朝7時半ごろに自動通知が入る仕組みになっています。

Skypeの時もSlackの時も、開始時にその日の作業を宣言することにしています。

また、Atusyが自由時間を得ると突発的に休日もくもく会が開催されます。
最初にその日のテーマを2、3分で話してもらい、数時間の作業の後に成果を10分とかで話してもらう感じ。

活動内容はだいたいこんな感じ。

そろそろ現地開催のイベントもやりたいなあという気持ちはありつつも、家庭との両立が難しくてできずにいます。

## 私にとっての朝もく

私はR言語もRコミュニティも好きなので、界隈が是非盛り上がり続けて欲しいし、盛り上げる側でもありたいなと思っています。

2020年の転職でPythonを使ったデータサイエンティストになり、2022年の転職でPythonとGoを使ったソフトウェアエンジニアになり、どんどん実用的にRを使う立場から離れています。

そんな私にとって朝もくは、Rと細く長く付き合える場です。

ろくに朝もくできない時期もありますが、他の方々が何かに取り組んでいるのを見て刺激をもらえるおかげで続いていると感じます。
別に誰にも強制されていませんが、誰かの挨拶に応えようとして、ならせっかくだし10分だけでもknitrのissueを見てみよう、とか。

また、なんやかんやと活動を続けているおかげで、本を執筆や、Tokyo.Rでの発表、Japan.Rでの企画などの機会も頂き、朝もくの良い課題になっていました（[Rが生産性を高める](https://gihyo.jp/book/2022/978-4-297-12524-0)）。

逆に、こういった機会に乏しい時期はRから離れがちかもしれません。
日頃から触れているものに興味は移りがちなので、最近は朝もくの時間にNeovimを触っていたりと、R以外のことをしている時間が増えました。

それでも最近は気が向いて、ftExtra 0.5.0のリリース作業を始めています。
放置している間にFedora環境でテストが通らない謎現象が発生しているので調査中……。

こんな感じでゆるゆる続けております。

## これからの朝もく

ちょっと課題に感じているのはメンバーが半ば固定されてきたことです。

その時々で活動量の多いメンバーは代わりますが、この1年、新しい人は入っていない気もします……。

地方コミュニティの難しさは、継続性にあると言います。
特に勉強会の場合は、冒頭でも述べた通り、場所と講演者の継続的な確保が難しいでしょう。
だからこそ、まずは活動を続けられることが大事と朝もくに励んできました。

とはいえ、このまま完全に参加者が固定して増えなくなると、遠くない将来、消滅しかねません。

来年は活動のアピールにもっと力を入れたいなと思っています。

年内、既に感じていた課題なので、解決案の一つとしてSlackのブックマークから簡単にハッシュタグとconnpassへのリンクをつけた投稿をできるようにしました。

> #OsakaR 朝もく https://osaka-r.connpass.com

しかし、私しか使っていません。

なので、Slack上での投稿に特別なキーワードが入っていたら、自動でTweetするBotとか作ってはどうかなど考えています。

数学系のもくもく会コミュニティではその日の参加人数をツィートしているので、真似してみてもいいかもしれません。
指定した時間帯の発言者数を自動集計して投稿する、とか。

ftExtraのリリース作業が終わったら、どうコミュニティを盛り上げるか考えることを私の朝もくテーマに据えようかな。

## ENJOY!!

本記事を読んで朝もくに興味を持って頂けた方は是非、以下のリンクから参加を検討していただけると嬉しいです。

https://osaka-r.connpass.com

