---
title: "vim-jpラジオ#25・#26聞いた - 2025年最初のテーマはEmacs！？"
author: atusy
date: '2025-01-16'
slug: vim-jp-radio-25
categories: [Vim, vim-jp-radio]
tags: []
output:
  blogdown::html_page:
    md_extensions: +east_asian_line_breaks+task_lists
highlighhtjs: []
summary: |
  VimmerもEmacsやろう！小指を鍛えて生き残ろう！
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = "#>", collapse = TRUE)
set.seed(123)
options(digits.secs = 0)
```

[#25]: https://audee.jp/voice/show/96517

[#26]: https://audee.jp/voice/show/97075

Vim-jpラジオ[#25]と[#26]はEmacs回。
ラジオ主催者のtomoyaさんもEmacsユーザーなこともあってついにこの日が来たかという感じ。
[#25]ではEmacsそのものの魅力について、組込み機能から拡張機能まで熱く語っていました。
[#26]ではさらにVimとの違いという観点で両エディタを深堀り。
Vim-jpはエンジニアの楽園と言われるだけのことはあって、コミュニティ名に直接関係ないことでもわいわい盛り上がってて良いところですね。
ラジオ内でもEmacsを主題としつつもVimやVSCodeもリスペクトしててよき。

[#25]は年明け初回ということもあり、正月のお話もちょっとでてました。
小さい子どもにお餅を食べさせていいものか、悩みますよねえ。
私は餅つき対応のホームベーカリーがあるので、うるち米を混ぜたりして食べやすくしていた記憶。
最近買い替えて、焼けるパンの量は微増したのに、つける餅の量は半減しました。

個人的にEmacsがおもしろいなと思ったのは、キーバインドで上下移動に<kb>Ctrl</kbd>+<kbd>n</kbd>や<kb>Ctrl</kbd>+<kbd>p</kbd>が割り当てられていて、QWERTY配列に依存しないところ。
Vimを始めた時は、hjklとホームポジションに移動系コマンドが集っててなんて便利なんだ！と思ったのだけれど、初心者を脱却するにつれて、hjkl以外の方法で移動することが増えるし、jjjkjkとかしていったりきたりする場面も少ないので、Emacsくらいの割り切りはいいものかもと思った。
jjjkjkとかするとしたら、コードリーディングの時くらいかな。
思考が中心のタイミングなので、高速な入力ができなくても困らないし、ホームポジションに集ってる必然性は薄そう。

こういう、違う視点を得られる機会って貴重だなと思いました。
みんな、Emacsもやろう！
小指が強い人しか生き残らないらしいけど！

冗談はさておき、実際に有名なVimプラグイン作者のShougoさんはEmacsの影響を強く受けているし、他の方が開発したプラグインの中にもEmacs由来のものがあったりして、広い世界を知るのは大事なんだろなあと思います。

Shougoさんと言えば、vim-jp Slack内で、Emacsはモードレスと言うけど`Ctrl`を押してる時だけモードが変わると考えることができるという話をしてて、この視点も実際にVimとEmacs両方を使ったことがあるから持てるんだろなと思ったり。

> そういえば、EmacsにもVimのような編集モードはあると思いますよ
> Vimの場合は切り替えがトグル式なんですが
> Emacsの場合はctrlを押してるときだけモードが移行すると考えると良いです
> シフトキーで大文字入力するのか
> capslockするのかの思想の違い

広い世界を知るためには、違う世界の窓となってくれる存在も大事なのだけど、Emacsは最近までそこに課題を抱えていた模様。
ゲストのたけてぃさんは、そこを解決すべく勉強会を開催してるそうです。
偉業だ……！

というわけで今回も皆さんの熱い想いを感じられる素敵なトークでした。

# ENJOY!
