---
title: 'Japan.RでTidy Tuesdayの企画した'
author: ''
date: '2021-12-05'
slug: japanr2021
categories: [R]
tags: [JapanR, OsakaR]
output:
  blogdown::html_page:
    md_extensions: +east_asian_line_breaks+task_lists
---

みんなEnjoyしてくれて成功。 \
でも個人的には反省いっぱいな会でした。

私はTidy Tuesdayの企画と、コミュニティ運営に関するパネルディスカッションのパネラーをしました。

今日は前者を振り返る。

# Tidy Tuesday

1時間という短かい時間でグループごとにNetflix titlesというデータセットを分析してもらいました。

## 準備頑張った

事前に[分析例](https://github.com/atusy/tidytuesday-netflix)を用意したり、その分析例を派生する[ネタ](https://github.com/atusy/tidytuesday-netflix/issues)を用意してみたり、限られた時間で色々やってもらえるよう手を尽くしました。
役に立ったかは不明。

また、事前アンケートを使ってRに不慣れな人が固まらないよう配慮しました。
こちらは良い感じに機能していたとレスポンスもらいました。

ただ、グループ分けに関してはもっと人数いてもよかったかもという意見をもらいました。
オンラインでやるとモブプロっぽくなるので、口出せる人多いほうが賑うのはその通りかも。
1時間で「めっちゃ凄い分析」みたいなのは無理があるので、なかなか機会のない「Rでワイワイする」を主題の一つに考えていたこともあり、それなら尚のことグループあたりの人数は多めでよかったなあと思います。

## 企画だけして当日いなかった

私が発起人となって企画したものの、虫刺されで急遽通院した結果、すべてをsoupcurryさんにお任せする事態に至りました。

それでもなんとかなったのは、こころよくバトンタッチしてくれたsoupcurryさんを始め、Japan.R運営のみなさんのおかげですね。

元々、家族の都合もあり、当日はグループワーク前後の挨拶とか説明的な部分で精一杯かもというのがあり、状況次第でsoupcurryさんに色々頼むかもとは言っていたのですが、まさかこんなことになるとは……。

通院したのは偶発的なものですが、こういう事情があるなら最初から企画に徹して当日は人に任せる方向に振っていてもよかったなあと思います。

## 感想戦には突如参入した

病院から戻ったら丁度感想戦の開始時間だったのでDiscordでわいわいしました。

意外と質問振ったら当日の空気感は掴めてよかった。

- 1時間は足りない
    - でも少々増やしたところで同じ
    - 予習したかった
    - データセットだけじゃなくて分析の方向性も絞る手もあったか
- グループ編成は良い感じ
    - 1グループあたり3〜4人で、アンケート結果を元にグループ間にレベル差が生じないようにした
    - 1グループあたりの人数はもう少し多くてよかったかも
- Rユーザー同士でわいわいする感じのイベントは新鮮で良い

要約するとこんな感じの感想を頂きました。

# Enjoy!

この精神を忘れず、来年もOsaka.Rなりなんなりで楽しい企画をできたらなと思います。



