[project]
name = "assets"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain>=0.3.24",
    "langchain-ollama>=0.3.2",
    "pydantic>=2.11.3",
]
