---
title: "Japan.Rで構造化ログについて発表した"
author: atusy
date: '2024-12-10'
slug: japanr-logging
categories: [R]
tags: []
output:
  blogdown::html_page:
    md_extensions: +east_asian_line_breaks+task_lists
summary: |
  オフラインイベントはリアクションがもらえて楽しい。準備や質問を通じて学びもいっぱい。またやりたい。
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = "#>", collapse = TRUE)
```

2024-12-07に開催されたJapan.R 2024で登壇しました。

> [Happy Structured Loggin in R（構造化ログ入門.R）](https://atusy.github.io/japanr-2024-logging/)

軽く、内容に関する振り返りと、発表そのものの感想をまとめておきたいと思います。
Osaka.Rについて話したことや、Japan.R全体の感想は別途書こうと思います。

# 内容振り返り

ざっくりとは以下のような内容で。

- ログの意義
    - 予期せぬ挙動や不安定挙動、パフォーマンス問題を発見・追跡するためのデータ
    - 分析を通じて改善に繋げられるよ
- ログのとりかた
    - 構造化ログを使うとログデータをプログラムに読み込みやすくていいよ
        - JSON Linesがデファクトスタンダード
    - スキーマも問題を追跡しやすいように工夫するといいよ
- デモ
    - ウェブアプリのログ分析を通じて問題の洗い出しと、改善方法の提案をしてみるよ

奇しくも今日はプロダクション環境でRを使う話が多かったので、参考になっていれば幸いです。
パッケージ開発やPoCでも役に立つので、積極的に採用してみてほしいです。
キーノートを飾ったHadley Wickhamもログの重要性に軽く言及してくれましたね。

発表のあとでXを確認したところ、試してみようとの声が聞こえ、嬉しかったです。
一方で、以下のような声も頂きました。

- なかなかログを残そうってところまで気持ちが追い付かないけどどこから始めたらいい？
- INFOログってどこまで出したらいいの？

このあたりについてはまた、別の記事でお答えできたらなと思います。

別にログの専門家ではないどころか、今回の発表のために必死になってログについて考えたくらいなのですが、どしどし分からないことを共有してもらえれば、可能な限りお応えしたいしだいです。
発表内容の用意もですが、頂いた質問でも、学びに繋がることが多くでありがたいかぎりです。

# 発表の振り返り

私にとって5、6年ぶりのオフラインでの登壇でした。
久しぶりだからかそわそわして、他の話があんまり入ってこなかった気がします。
でも、視聴者の反応をリアルタイムに感じられるのはいいものですね。
またやりたい。

- printデバグしたことある人？と聞いて挙手してもらえた
- HadleyがCSVよりParuquetを使ってこうよと言うけど、CSVファイルがもらえるだけマシと思う人も多いはずと言ったら、大勢が頷いてくれた
- 天気予報サービスのデモで、同じ地域の情報を数秒ごとにリクエストして、しかもその処理が何秒もかかっちゃうの無駄だよね、そんな短時間で予報が更新されるわけないし、ユーザーも期待してないよねってビジネス上の背景を理解してキャッシュを検討するといいよね、という話にくすっとウケてくれた

こういう反応、ありがたいです。
聞いてもらえてるな、面白がってもらえてるな、という感触を掴めます。
テンションが上がりますし、次への励みになりますし、心の掴みかたを学べます。

構造化ログ入門という少しスコープ広めの話をしましたが、個人的に頂いたフィードバックもふまえると、printデバグの延長線としてログを使ってみる話とかできると、更にログの魅力を感じてもらえるのかなとか、アイデアにも繋がりますね。

良い成果を、良いコードで生むためにはドメインへの深い理解が必要だと思ってて、このあたりの話も案外ウケるのかもなーと思いました。

ともあれ、デモも含めて20分枠にぴったりおさまってよかったです。
ただ、その場にじっとして話すの性に合わないので、ポインタを持ちたい気がしました。
Hadleyみたいに歩き回りたいですね。

# ENJOY!!

またどこかの会場でお会いしましょう！
