---
title: "Nix Meetup #3 大阪に参加した"
author: atusy
date: '2025-05-28'
slug: nix-meetup-3-in-osaka
categories: [Tech]
tags: [nix, nix meetup]
output:
  blogdown::html_page:
    md_extensions: +east_asian_line_breaks+task_lists
highlightjs: []
summary: |
    Nix meetup #3 大阪が2025-05-24に開催されました。
    技術への愛溢れた濃いい話がいっぱいできてよかったです。
    いっぱい聞けて、じゃなくてできてってところがまた素敵。
---


Nix meetup #3 大阪が2025-05-24に開催されました。

> <https://nix-ja.connpass.com/event/353532/>

技術への愛溢れた濃いい話がいっぱいできてよかったです。
いっぱい聞けて、じゃなくてできてってところがまた素敵。

休憩や懇親会では、Nixの話に限らず、IT界隈の凄い人談義や、職場での目標のありかたなど、広く話せた。
オフィシャルな懇親会は食事なしで開かれたのだけれど、かなり盛り上がってた。
その後、特に予約もないのに参加者全員で飲み屋へ行ったくらいなので、みんなの満足ぶりが伺えますね。

この空気感のよさは主催者がうまく醸成してくれてるなと感じました。
とくにたけてぃが、登壇者への質問を積極的にしてくれるのだけれど、本当に楽しそうで、無理にひねり出してる感がなかったのがよかった。
そのおかげかどうか、参加者全体からも、質問が出てた印象。

個人的には、何名かの方からブログ読んでます！と言ってもらえたのも嬉しかったり。

ちなみに第一回と第二回は東京で開催されてたらしい。
今回大阪で開催されたのは、遊びに来たかったからなのかな？
Nixおもしろいけど、そのために東京……！というモチベーションがない勢は私に限らずそれなりにいるっぽかったので、すごくありがたい。

当日の様子はXのハッシュタグ[#nix_ja](https://x.com/search?q=%23nix_ja&src=typed_query&f=live)でも少し見れるかも。
私はWiFiがなかったのもあってあんまり投稿してなかった。

それから、エディタや環境関連の勉強会は、自分と少し離れた業務領域の人と関りが持てるのも楽しみの一つだなーと思った。

次もぜひ参加したいですね。

以下、発表の感想戦。

- [Nix 式としてドキュメントを取得できるといいよねという話](https://scrapbox.io/kakkun61-scraps/Nix_%E5%BC%8F%E3%81%A8%E3%81%97%E3%81%A6%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88%E3%82%92%E5%8F%96%E5%BE%97%E3%81%A7%E3%81%8D%E3%82%8B%E3%81%A8%E3%81%84%E3%81%84%E3%82%88%E3%81%AD%E3%81%A8%E3%81%84%E3%81%86%E8%A9%B1) by kakkunさん
    - Nixって関数の引数情報とか取得しにくい問題との戦い
        - 言語を拡張したいよね、TSみたいにトランスパイルすればよさそうよね
        - でも現実的にそこまでするの大変だからfunctorにdoc属性を持たせるといいんじゃない？
    - LuaとかJSとかみたいに、コメントでドキュメント・型をつけれると、トランスパイルもいらんし、LSPで解決できていいよねって話した
    - 個人的に一番好きな発表
        - というのも、似たような課題感で[RでPython風docstringを実装してみる](https://blog.atusy.net/2021/12/20/r-docstring/)という記事を書いたことがあるから
- Nix OverlaysとEmacs Org-modeによる研修システムの構築 by klehaさん
    - 高専の課外活動（？）をうまく回すためにNixを導入してる話
    - 高専すげえってなった
    - Nixのおかげで、環境問題を回避して、研修を受けやすくなったらしい
    - でも引き継ぎは考えたくないと受講者に言われたとか
- [賢いとは言えない私がどうやってNix に入門したのか](https://speakerdeck.com/xantibody/xian-itohayan-enaisi-gadouyatutenix-niru-men-sitanoka) by raizawa1600800さん
    - Nixを紹介する人の記事、賢すぎでは……？と感じてたので、すごい共感が多かった
- [NixでMacの全ての環境構築ができた](https://scrapbox.io/mrsekut-merry-firends/2025%2F5%2F24_Nix%E3%81%A7Mac%E3%81%AE%E5%85%A8%E3%81%A6%E3%81%AE%E7%92%B0%E5%A2%83%E6%A7%8B%E7%AF%89%E3%81%8C%E3%81%A7%E3%81%8D%E3%81%9F_@Nix_meetup_%233) by mrsekut（まる）さん
    - 自分のユースケースと近いところの話で、うんうんとうなずきながら聞いていた
    - nix-darwinだとApple Store経由のアプリなんかも管理できるらしい
    - 私はパッケージ管理くらいにしか使えてないけどまるさんみたいにOSの設定もNix化したいなあ
    - この話がきっかけだったかな？`terraform import`みたいにNixも現状からNix式を生成するコマンドがあるといいよなあと雑談した
    - package by featureで構成してるらしい
        - <https://github.com/mrsekut/dotfiles/tree/master>
- Twist.nix での Emacs 設定管理する by Kyure_Aさん
    - Emacsのことはよくわかってないけど、便利なものを作者以外の人が紹介するのっていいよね
    - 特に、Twist.nix公開以降のエコシステム進化に追従するためのTipsが詰まってるのはすごくいい
    - ぜひ本家のドキュメントにPRしてほしいですね
    - ちなみに[Twist.nix で再現性のある Emacs 設定を作る](https://zenn.dev/kyre/articles/b1959567edfc15)という記事をベースにした発表だったそうです
- [tmux-nixの実装を通して学ぶNixOSモジュール](https://speakerdeck.com/momeemt/tmux-nixnoshi-zhuang-wotong-sitexue-bunixosmoziyuru) by momeemtさん
    - tmuxの設定は`programs.tmux`を通じてできるらしいのだけど（参考：<https://nixos.wiki/wiki/Tmux>）、細かい設定は結局`extraConfig`にtmux.conf相当の内容を書くのだとか
    - あとプラグインサポートも貧弱らしい
    - このあたりの課題に対してtmux.confを使わずtmuxを設定できるNixOSモジュールを作っているらしい
    - すごい情熱
    - ここから実装の詳細に入ると思いきや、タイトル通り、NixOSモジュールの紹介をしてくれたり、テスト方法を紹介してくれたり、広く刺さる内容でよかった
    - tmux本体のドキュメントを参考にひたすら書いてくから、AIにやらせちゃうとよさげってのはなるほど感があった
    - 本題と趣旨はずれるけど、個人的にはNixにロックインされたくないので、プログラムの設定はNix式でなく本来の設定ファイルで書く派


**ENJOY!!**
