---
title: "変わったと言っちゃえ"
author: atusy
date: '2025-04-29'
slug: the-changing-same
categories: [Essay]
tags: []
output:
  blogdown::html_page:
    md_extensions: +east_asian_line_breaks+task_lists
highlightjs: []
summary: |
    わずかな変化でも認めてあげることが大事だなと、ふいに思ったのだ。
---

```{r setup, include=FALSE}
```

少し前に、今まで放置しがちだったことをやれるようになった、変わったという話をした。

> 来たときよりも美しく \
> <https://www.uta-net.com/song/81025/>

私を実際に知る人からしたら、え、言うほど変わった？と聞かれるかもしれない程度の変化かもしれない。
それでも、書きながら「変わった」と言ってしまえ、認めてあげろと思ったのだ。

また別の記事で綴った、言葉の呪術めいた力を借りたかったのだ。
記事では呪術めいた力の負の側面に焦点をあてたけれど、自らを後押しする力にもできる。

> 言葉の受け売りにご用心 \
> <https://note.com/atusy/n/n5470e1b9c289>

せっかく1つでも行動にできたのだから、「変わろうと思う」とか「まだ変われてない」だなんて遠慮することはない。
遠慮して、偉大な一歩を矮小化してはもったいない。

もちろん、何もしてないのに「変わった」と言うわけにはいかないので、言えるようにハードルを低くしていくのも重要なテクニックだなと思う。

検査可能な小さなトライを用意する力と、実際に検査し言語化する力を得て、私は自分を変えられるようになったぞ！
やったね！

**ENJOY**

というわけで本題は終わりだけど、この記事のURL入れた`the-changing-same`は、平井堅の「The Changing Same - 変わりゆく変わらないもの -」からもらった。
この曲から、変わってく中にある変わらない芯みたいなものの美しさを感じていた。
今日聴きなおして、己であり続けつつも変わっていく様子にも美しさがあるのだなと気付いて記事執筆のきっかけを得た。

最近、一人綴る言葉、仲間と交わす言葉、書籍や音楽から受け取る言葉、これらの交わりを感じることが増えた。
言葉を愛おしく思う日々だ。

