---
title: "Tokyo.R 90でRStudio PBCに転職しようとした時の話をした"
author: ~
date: '2021-03-11'
slug: tokyor90
categories: [Tech]
tags: [R, TokyoR]
output:
  blogdown::html_page:
    md_extensions: +east_asian_line_breaks+task_lists
summary: |
  Tokyo.R 90でもBoothの頒布物でも語っていない裏話。
---

Tokyo.R 90でRStudio PBCに転職しようとした時の話をしました。
その時の資料 (無料) とその詳細版+応募書類の実例 (100円) はBoothで頒布してます。

> https://atusy.booth.pm/items/2796523

そういえば給料の話をTokyo.Rでしたところ、懇親会で高いのか安いのか分からんと言われました。
私も分かりません。
誰か教えてください。

さて、この記事では発表や頒布物で語らなかったところを少し書こうと思います。

# なぜこの話題をTokyo.Rにもっていったのか

肝心なところを語りませんでした。

1. CJK（Chinese Japanese and Korean Language）ユーザーの多いRStudio製品にはCJK民が参加した方がいい
1. 珍しい話題で興味のある人がいそう

この2つが理由です。
特に1つ目は結構大事です。
パッケージにしろRStudio IDEにしろ、非欧文文化圏故の問題に遭遇することは珍しくありません。
RStudio IDEの場合、エディタ上での日本語変換に困ったなんて話はよく聞きましたね。
尚、私はRStudio Serverを使っているおかげでこの問題を回避できているので、RStudio Desktopの現状を把握できていません。
それでもスペルチェック機能を使うとひらがなとカタカナに波線が表示されて辟易しています。

こういう問題に遭遇した時、声の大きい人がいるか、声を挙げる人が大勢いるか、は改善に大いに影響します。
最近だとrmarkdownパッケージの開発に盲目の方が関わってくれていて、おかげで彼以外の開発者もアクセシビリティを意識する傾向にあります。
あとは`knitr::kable`関数の列の文字揃えが日本語を含むと失敗する問題があったのを私が直したりしました。

というわけで自分の発表でRStudioに挑戦してみようって人が現れると良いなと。
私にできる範囲でしたらアドバイスしますよ。
応募書類のレビューなどに付き合ってくれたホクソエムの面々もきっと協力してくれるはず。

# なぜ詳細版は有料で頒布することにしたのか

応募書類を筆頭に個人情報の塊なので、無料で誰でもアクセスできる状況はちょっと気がひけました。

# なぜ詳細版をBoothで頒布することにしたのか

今時、この手の資料を有料公開する方法としては[note](https://note.com)や[Zenn](https://zenn.dev)など、いろいろとあります。
そんな中、なぜBoothを選んだのか。

## 書式の自由度

noteやZennはブラウザ上で閲覧可能な記事の形をとります。
一部を無料公開することもでき、支払ったらすぐに読める点が高いUXを提供すると思います。
一方でBoothはPDFやzipなどをダウンロードしてもらう手間が生じます。
この点でnoteやZennを最初に考えました。

しかし、noteは階層的な章構成を作れません。
そこそこの文章だったことと、プラットフォーム選出前にMarkdownで下書きして既に階層化していたこともあり、noteを候補から外しました。
書式の自由度と引き換えのシンプルさが魅力だと思うので、ここは使い道の問題です。

ZennはMarkdown記法が使え、本レベルのものを有料公開しようというスタンスなので、自由度としてはマッチしました。
応募書類やそのソースファイルであるRmdファイルを共有する機能はありませんが、GistやDropboxなどと組み合わせれば間に合う話です。
というわけで候補に残りました。

この時点でBoothは候補から外すほどではないが、Zennの方が優勢でした。
ただ、Boothでは商品ページにSlideShareの内容を埋め込める点に多少の魅力を感じていました。
無料版と有料版の入口を統一できます。

## 最低価格

有料公開の場合、note、Boothは100円、Zennは200円からです。
今回、有料にしたのは、読者のフィルタリング程度の意識だったので、安く公開できる方がいいなと思いました。
とはいえ、200円でも全然惜しくない内容だろうと思っています。

この時点でBoothとZennが拮抗しました。

## 著者の負担

大々的に稼ぐ目的でもないので、私の負担は最小限にしようと思いました。

実はBoothとZennが拮抗したところで、使ったことないからZennにしてみようかなとも思いました。
zenn-cliをインストールしたりGitHubレポジトリと連携したりと手も動かしました。
しかし色々と調べるのが面倒になってしまいました。

そこでふと、SlideShareも使ったことがないなと思い、
Boothで商品ページにSlideShareの内容を埋め込むのを試すことにしました。

# Enjoy!
