---
title: "朝もくを1ヶ月して得た教訓とか #OsakaR"
author: ~
date: '2020-05-10'
slug: my-way-of-asamoku
categories: [Osaka.R]
tags: []
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

Osaka.Rの活動としてリモート朝もくを始め1ヶ月ほどが経過しました。
良い機会なので、その過程で得た教訓とかをまとめておきたいと思います。
必ずしも毎回守れているわけではありませんが、
大事にしていきたいので宣言もかねてblog化しました。

朝もくには、大阪府外の方も7時半から10時までの間で自由に参加できます。
アカウント不要でブラウザ動作するチャットツールSkypeを利用しています。
詳細は <https://osaka-r.connpass.com/> からどうぞ。
皆さんの参加お待ちしています。

# 目標を宣言しよう

有言実行できると自信とモチベーションに繋がります。
目標はぜひ宣言しましょう。

## 朝もくの間に達成できる粒度の目標を作ろう

Osaka.Rでは8時から10時を朝もくの時間としています。
ただし、各人の用事に合わせて途中参加や途中離脱を可能としています。
私の場合は9時から仕事なので9時前には抜けています。

実質的な作業時間は1時間未満でやれることは限られています。
限られた時間の中で多少なりとも進捗を出さないと、徐々にモチベーションが下がります。
朝もく参加しても大して何もできないし……となるわけです。
そこで、本を1ページ読むとかでいいので、自分の時間で確実に達成できそうな目標を一つたてておきましょう。
目標より進んだ? Gooooood job!!

適切な粒度の目標をたてる能力も養えて、マネジメント力もアップするかもしれません。

ちなみに明日からは開始を30分早めて7時半にします。

## 色々やろう

毎日同じ課題に取り組んでいるとだれてしまう場合は、曜日によってやることを変えてみてはいかがでしょう。
私は月曜日はblogを書く日にしています。

# 進捗は報告しよう

目標は達成できるに越したことはないですが、義務ではありません。
達成できなかったならできなかったなりに、どれだけできたか報告しましょう。
明日へのバネにしましょう。
達成できたらみんなに褒めてもらいましょう。

# 互いを褒めよう

絵文字を送るので十分なので、目標や進捗にイイネしましょう。
そっと背中を押されているのは私だけではないはず。

# 別のコミュニティも利用しよう

具体的な目標や進捗を言えると良いですが、なかなか表に出せないことをやっている人もいます。
私もその一人です。
そのような場合は、Osaka.Rだけではなく、自信の所属する別のコミュニティに報告すると良いです。

# アウトプットしよう

できればですが、blogなどに成果を公表しましょう。
公表するつもりでもくもくすると、己への甘えが少し減ります。

# Enjoy!!

何より楽しむことが大事ですね。
無理のない範囲でやりましょう。