---
title: "vim-jpラジオ#27・#28聞いた - 実はEmacs30年選手！t-wadaさん登場！"
author: atusy
date: '2025-01-28'
slug: vim-jp-radio-27
categories: [Tech]
tags: [Vim, vim-jp-radio]
output:
  blogdown::html_page:
    md_extensions: +east_asian_line_breaks+task_lists
highlighhtjs: []
summary: |
    分かるところからやってけ
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = "#>", collapse = TRUE)
set.seed(123)
options(digits.secs = 0)
```

<!--
- 年始の収録。ありすえ家はインフル
- Emacsのきっかけは大学でのすりこみ。日本語を使えた。メール専用ソフトの役割も担った。
- Emacsあんまり落ちないから起動しっぱなし
- きのこ本。日本人10本追加で107本 <https://techblog.cartaholdings.co.jp/entry/carta-kinoko-book-2024>
- 金のない大学生がLinux, Emacs, GCCを使えた。恩を感じる
- EmacsのパッケージはGPLライセンスで公開。貢献の連鎖。誇らしい
- 企業によるOSSへのフリーライド

- Emasいつ使う？
  - 1人で作業するとき
  - でも言語による
      - Java: IntelliJ
      - Rust: VSCode
  - 経費生産はEmacs
      - スクラッチバッファ
      - その場かぎりの計算とかに便利
      - TDDに繋がる
- ペア・モブはVSCodeとかIntelliJとか
  - 技術顧問・コンサルとして一緒にコード書いて知見とか技術を残すのが仕事だから
- いろんなエディタを使うけど、20年くらいペア・モブやってるので、訓練済み。モードがきりかわる
  - Kent Beckが自分の好みとチームの生産性どっちをとるの？
- リモートだと好きなキーボード・キーバインディング使えるのはいい
- REPL駆動開発
    - ちっちゃい式を書いて実行して、組み合わせていくことができる
    - documentとかもEmacsの中で見れる。完結している。
- TDD
    - Emacsだな
    - これは動くなと分かってるものを組み合わせて複雑なものを、破綻なく作る
        - 上から作るのとは違う
            - 自分たちの設計はだいたい間違ってる
        - Unixカルチャ
        - 小さいものから作ってもだいたい間違ってるけど、全滅しない。部分部分は生き残る。7・8割
            - 生き残ったものを組み合わせていく
            - 変化にたえる
    - 最終的なゴールが見えてるからTDDできるんですねって言われる
        - じっさいにはわかってない
        - 仕様が分からないから分かるところからテストを書く
        - わかってないもの・複雑なものに対するプラクティス
    - tomoyaさんもすっと入れた
        - 目の前のできることから始めればいい
    - 複雑なものを破綻なく

- https://levtech.jp/media/article/column/detail_496/
    - うまくテストが管理されていると10分とか短かい時間でCIがおわる
- 画面上のテストをどうかけばいいかわからない
    - インタラクションがある・変わりやすいでむずかしい
    - VRT・storybook・playwrightのE2Eなど書けるところから。単体テストには軸足をうつせばいい。最初はどんな粒度でもいい。頑張りすぎない。網羅率も気にしない。コスパに合わせて。
- Findy開発生産性カンファレンス2025にKent Beckがくる
- 次回はゲストなしで半年を振り返る
-->



[#25]: https://audee.jp/voice/show/96517

[#26]: https://audee.jp/voice/show/97075

[#27]: https://audee.jp/voice/show/97837

[#28]: https://audee.jp/voice/show/97837

Vim-jpラジオ[#27]と[#28]はt-wadaさんをゲストに迎えたEmacs回でした。

- [【実はEmacs30年選手！t-wadaさん登場！】エンジニアの楽園 vim-jp ラジオ #27][#27]
- [【TDDへの理解とEmacs】エンジニアの楽園 vim-jp ラジオ #28][#28]

[#25]と[#26]もEmacsがテーマだったので、本編でも言われるように実質Emacs radioでしたね。
Emacsの魅力を通じてVimを再解釈できるステキな回でした。

> [vim-jpラジオ#25・#26聞いた - 2025年最初のテーマはEmacs！？](https://blog.atusy.net/2025/01/16/vim-jp-radio-25/)

[#27]・[#28]ではEmacsについて語る……と触れこんでますが、 実はEmacsというコアな部分を持つことで生まれたもの、得られたものの話だったように感じます。
Emacsを始めとしたOSSの存在にどれだけt-wadaさんが助けられ、成長したのかといった話や、EmacsにおけるREPL駆動開発がいかにテスト駆動開発の理解を促したかといった話がでてきます。

どちらの回もEmacsが起点で、Emacsの魅力に溢れてるわけですが、だからEmacsをやれとかそんな単純な話じゃない。
新しい世界に触れることや、逆にコアの部分を大事にすることで、独自の視点が養われ、人として成長していくんだなと感じました。
なんかこう書くと当たり前すぎる……。

t-wadaさんがゲストなこともあり[#28]ではテスト駆動開発（TDD）もがっつり掘り下げてます。
TDDが変化に耐えるソフトウェア開発を加速する認識はあったのですが、分かる小さいところから作っていく方法論でもあるという認識は新鮮でした。
確かに仕様の全容が見えない大きなものを作る上で、まず分かるところから小さく作っていくというのは理にかなっているように思います。

おたよりへの回答では、テストの粒度や網羅率についても気にしすぎず、やれるところからやって単体テストの比重を高めていけばいいよというアドバイスをしていて、「まず分かるところから」という考え方が徹底されているなと感じました。

ところでREPL駆動開発といえば、私もRStudioで分析やパッケージ開発をしていた頃は、コードを部分的にREPLに送り込んで動作を見ながら開発していました。
RStudioでの経験から、現在の開発でもREPLやシェルで試している内容をテストに書いていくというやりかたをすることがあります。
タイミング次第でテストファーストになったりならなかったりするのですが、わかるところから仕様を固めていくというやり方が共通しているなと感じました。
また、わかるところから書いていくと、全体が破綻するようなケースは少なく、捨てるコードも2、3割程度で済むという話も共感できました。

余談ですが、こう感じられたのは、感想を書くつもりで話を聞いていたからかなとも思います。
学習ではアウトプットを前提にしたほうがインプットの質もあがるよとはよく言われます。
インプット対象が他者の経験談などになると、人を自分の鏡にして自己理解も促進されると気付けたのは、ちょっとした収穫に思います。

次回でvim-jpラジオは半年を迎えるとのことです。
特段、めっちゃ良い話をするぞと肩に力を入れてらっしゃるわけではないと思うのですが、ただでさえ聞いてて楽しいラジオが、これからも色んな気付きをあたえてくれそうで、楽しみにしています。

## ENJOY!


