---
title: bookdown のコミッタになったのでこれまでの貢献を振り返る
author: ~
date: '2019-07-07'
slug: bookdown-committer
categories: [Tech]
tags: [R, R-rmarkdown, R-bookdown]
---

bookdown のコミッタになった．
ほんまにええんかいなと思いつつ，貢献を続けていく上で励みになるので，ありがたく頂戴した次第．

私が過去に出した PR が Pandoc の仕様変更に巻き込まれたので，どうするか相談していたところ，

> 君の Issues や PRs はいつもわかりやすいから，書き込み権限が欲しくなったらいつでも言ってくれ．喜んで承認するよ．
> (原文: Since your issues and PRs are always so clear, just let me know if you want write access to this repo someday, and I'll be happy to grant it to you)

と言ってもらえた．嬉し過ぎでした (<https://github.com/rstudio/bookdown/pull/706#issuecomment-508875390>)．

ちなみに R Markdown 関係でこれまでにした PR は8件で内5件がマージ，2件がマージ待ち，1件がマージせずにクローズ．
Issues は3件．
ちなみにマージ待ちの案件が片付いたらやりたい PR がまだある．
気負う気はないが，コミッタに相応わしい貢献をしたいところだ．

以下，私の関わった PRs と Issues 一覧．チェックしてあるものは closed．

- knitr
    - [x] [#1703 Issue](https://github.com/yihui/knitr/issues/1703):
      R チャンクで生成した画像に id 属性を与える機能が欲しいと言われたのでもうあると答えた，
    - [x] [#1710 PR](https://github.com/yihui/knitr/pull/1710):
      Pandoc の fenced code attribute をチャンクオプションから指定できるようにした．
    - [x] [#1715 PR](https://github.com/yihui/knitr/pull/1715):
      knitr のテスト方法は特殊なので，説明文を `CONTRIBUTING.md` に追加した．
    - [x] [#1727 PR](https://github.com/yihui/knitr/pull/1727):
      Travis CI でテストをパスできるように yaml を修正した．
- rmarkdown
    - [x] [#1557 Issue](https://github.com/rstudio/rmarkdown/issues/1557):
      Pandoc 2 にするとチャンクオプションの `indent` を指定した時の挙動が正常化したという報告に対し，
      いつの更新によるものか調べて追加報告した．
    - [ ] [#1597 PR](https://github.com/rstudio/rmarkdown/pull/1596)
      `html_document` で，結果を示すコードブロックに行番号を与えると，背景色が白から灰色になってしまう問題を修正．
    - [ ] [#1598 PR](https://github.com/rstudio/rmarkdown/pull/1598):
      `html_document` のコードブロックの背景色が適切に適用されない不具合を修正．
- bookdown
    - [x] [#705 Issue](https://github.com/rstudio/bookdown/issues/705),
          [#706 PR](https://github.com/rstudio/bookdown/pull/706):
      `bookdown::html_document2` やそれに依存する `output` がコードブロックに行番号を与えられない問題を修正した．
    - [x] ~~[PR #738](https://github.com/rstudio/bookdown/pull/738)~~:
      様々な output でコードブロックの表示を改善したかったが，考え直したくなったので close.
- pagedown
    - [x] [#100 PR](https://github.com/rstudio/pagedown/pull/100):
      コードブロックに行番号をつけると，折り返したコードの表示がおかしくなるのを修正した．
    - [x] [#106 PR](https://github.com/rstudio/pagedown/pull/106):
      推奨する Rstudio のバージョンが1.2系のプレビュー版のままだったので正式版に変更した．
