---
title: "オレのNeovim見て！"
author: atusy
date: '2024-12-09'
slug: awesome-my-neovim
categories: []
tags: []
output:
  blogdown::html_page:
    md_extensions: +east_asian_line_breaks+task_lists
summary: |
  (TODO)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = "#>", collapse = TRUE)
```

- Vim/Neovimってターミナルと仲良しな人向けのあれでしょ？
- 文字入力や保存・終了すら直感できない初心者殺しのあれでしょ？

まあそうかもしれないけど、今日の話で、ちょっとでも興味もってもらえると嬉しいな！

# Neovimとは？

2014年にVimから派生したテキストエディタ。
Vimからとの互換性を極力保ちつつ、新しい機能の追加・変更を行っている。

- LSPクライアントの内蔵
- AST解析機能
    - シンタックスハイライトなどに使える
- terminal emulator
    - Vimも後追いで対応
- floating window
    - Vimにはpopup windowという似た機能があるが、フォーカスできない（現在対応中）
- Lua言語による設定

といってもforkから10年が経ち、**できること**の差は小さくなっている気がする。

# なんでVim/Neovimなの？

かっこいいから！はTRUEだけど……。

本質的にはモードというコーディングに適した機能があるから。

**コーディング ≠ 文字入力**なので、案外文字入力（インサート）する場面は限られる。

- 準備
  - ファイル選択
  - カーソル移動
- コードリーディング
  - 関数の使い方確認
  - 検索
- 文字入力によらない編集
  - コピペ
  - 置換
  - Undo/Redo
  - 行結合

など。

Vimでは文字入力しないノーマルモードを中心として、様々なモードを行き来する。

```
ノーマルモード ⇔ インサートモード（文字入力）
                  ビジュアルモード（文字選択）
                  コマンドラインモード（検索・置換などいろいろ）
                  ...
```

ノーマルモードでやるには複雑すぎることは他のモードに任せる。
終わったらノーマルモードに戻る。

え？複雑だって？インサートモードだけの世界観で色々やってるほうが複雑なんよ！
モードごとにやること絞ってるほうがシンプルっしょ！
（諸説あります）

# まあとりあえずオレのNeovim見て！

プラグインましましだから色々できるよ！

## 補助ラベルによる功利的な操作

### カーソル移動

- 行内のあの文字の場所に行きたい
- 視野内のあの文字列の場所に行きたい
- 検索でマッチしている場所に行きたい

### 範囲選択

- 文法的に意味のある範囲を選択したい 
  - 折り畳みなんかにも使える

```python
def fizzbuzz(n):
    if i % 3 == 0 and i % 5 == 0:
        return "FizzBuzz"
    if i % 3 == 0:
        return "Fizz"
    if i % 5 == 0:
        return "Buzz"
    return i
```

### 括弧などの囲いの操作

#### 囲い文字の置換・削除・追加

##### 置換: () -> []

surroundingをreplace
^            ^

- sr([

```python
x = (1, 2, 3)
y = (1, 2, 3)
z = (1, 2, 3)
```

括弧じゃなくて""とかも操作できる

二重→一重とか

```python
txt = "Hello, world!"
```

##### 削除: ()

surroundingをdelete
^            ^

- sd(

```python
# ()をなくしたい
# ()の中で`sd(`
def f():
  return (1, 2, 3)
```

##### 追加: []

surroundingをadd
^            ^

- <範囲指定>sa[
  - v$sa[
- sa[<範囲指定>
  - sa[$

```python
def g()
  return 1, 2, 3
```

```markdown
日本語のかっこも操作できる

（かっこ）を「」にかえる
（かっこ）をけす
かっこをつける
```

#### 囲った範囲の操作

`vi"`とかすると、`""`の中身を選択して、操作できる

``` python
txt_ja = "Hello, world!"
txt_en = ""
```

### ウィンドウの移動

基本のウィンドウ移動はhjklによる左上下右のカーソル移動のアナロジー。

`CTRL-W` + `CTRL-K`すると上にあるウィンドウに移動する。

でも、上ってどれ？という場面がある。

ラベルがあれば一発。

## 意識の集中

ウィンドウの背景色に意味を持たせる。

- 選択中のウィンドウ
- プロジェクト外のファイルを開いているウィンドウ
- その他

## Gitと仲良く

## FuzzyFinder

## AIとも連携できる


# fizzbuzz直す

```r
fizzbuzz <- function(n) {
  if (n %% 3 == 0) {
    return "Buzz"
  }
  if (n %% 5 == 0) {
    return "Fizz"
  }
  if (n %% 15 == 0) {
    return "FizzBuzz"
  }
  return n
}
```

- Rの`return`は文ではなく関数なので`()`が必要
- 15の倍数を先に判定すべき
- 3の倍数のときはFizz
- 5の倍数のときはBuzz

# これから始める人へ
