---
title: "Neovim 0.13（開発版）にテキストオブジェクトが増えるらしい。ilで空白を除いた1行、alでバッファ全体だってよ"
author: atusy
date: '2026-05-20'
slug: nvim-textobjects-il-and-al
categories: [Tech]
tags: [Neovim]
output:
  blogdown::html_page:
    md_extensions: +east_asian_line_breaks+task_lists
---

本記事は2026-05-20の[Vim 駅伝](https://vim-jp.org/ekiden/)の記事です。

## テキストオブジェクトについて

皆さんテキストオブジェクト使ってますか？

テキストオブジェクトを使うと、操作（y, d, cなど）の範囲指定がとても楽になります。

たとえば単語をdeleteしたいとしましょう。

テキストオブジェクトを使わない場合は、`bde`といった具合に、`b`でカーソルを単語先頭に移動してから、`d`でdeleteを開始して、`e`で単語の末尾までを範囲に指定する、という流れになります。
カーソル合わせが面倒ですね。
特にドットリピートしたい時は、カーソル合わせが頻発します。

ところが、`iw`というテキストオブジェクトを使えば、`diw`でカーソルを含む単語をdeleteできるため、カーソル位置はざっくりでよくなります。

様々なテキストオブジェクトが標準に存在しているので、使ってみてください。

> <https://vim-jp.org/vimdoc-ja/motion.html#text-objects>

## 新しいテキストオブジェクトの`il`と`al`について

さて、ようやく本題。
タイトル通りなのですが、Neovim 0.13（開発版）に新しいテキストオブジェクトが追加されました。

- `il`
    - 空白を除いた1行
    - inner lineと覚えるとよさそう
- `al`
    - バッファ全体
    - all linesと覚えるとよさそう

> <https://github.com/neovim/neovim/pull/39845>

`il`は割と定番の設定として知られてきたものですね。
古くからあるVimプラグインでも実装されています。

> <https://github.com/kana/vim-textobj-user>

ところで、このプラグインでは`al`は空白も含む行全体をChar-wiseに選択するものでした。
伝統的（？）なall linesに相当するものは`ae`で知られています。

> <https://github.com/kana/vim-textobj-entire>

伝統的なプラグインの定義とNeovimの新たな定義、どちらを好むかはユーザー次第かなと思います。

## 私の設定について

ちなみに私は今まで`al`も`il`も設定してませんでした。
行全体選択の`al`に需要がなかったこと、`il`がキーが近くて打ちにくいことが理由です。
inner lineには`ii`をマッピングしていました。

でも今回を機にNeovimに寄せてみようかなと思ってます。

`al`がバッファ全体で本当にいいの？と思われるかもしれませんが、行全体選択としての`al`は以下の理由で相変わらず不要と思ってます。

そもそも、ほとんどの場合は`yy`, `dd`, `cc`といった行単位の操作で十分と感じています。

ただし、これらは改行も操作対象にするため、`yyp`は現在行を新しい行にputするし、`dd`は現在行がなくなるので、若干不便なケースもあります。
こういったとき、`yal`や`dal`が使えると、改行を除いた操作ができるわけですね。

しかし、`0Y`や`0D`で十分対応可能と感じます。
カーソルの位置合わせの負担がないことに加え、これらの操作でドットリピートしたいケースがまずないからですね。

`0D`でドットリピートしたいときも、`0`で行頭にカーソルを持ってきてしまえば`0Dj.j.j.j.j.`できるので特に困りません。

と思ってるのですが、もし行選択としての`al`がめっちゃ便利なんだよーとかあればぜひお知らせください。

## ENJOY

Neovimの更新をウォッチしてると、気付きがあって楽しいですね。


