---
title: "週刊アトデ 2024-11-22"
author: atusy
date: '2024-11-22'
slug: atodeyomanakata
categories: [Tech]
tags: [アトデ]
output:
  blogdown::html_page:
    md_extensions: +east_asian_line_breaks+task_lists
highlighhtjs: [bash]
summary: |
  アトデヨム、ウソジャナイ、ヨムノタノシー
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = "#>", collapse = TRUE)
```

あとで読もうと思って一生浮上しないものがいっぱいあるので週ごとに振り返ろうと思い、blogにしてみる……。
とりあえずSlackの「後で」とXのLikesから抽出。
こうしてみると、あとで読もうと思ってたはずがピンどめすらできていないものも多数ですね……。

## イマヨンダ

- [スプリントゴールって何？](https://miholovesq.hatenablog.com/entry/2022/07/29/120418)
    - Ryuzeeさんがこれさえ読んでおけばいいと言ってたやつ
    - 最近、職場でスクラムを始める準備をしてるので、ちょっと気になる分野
    - プロダクトバックログアイテムの達成をゴールにしちゃうと柔軟性がなくて本質を見失うとのこと
    - それはそうかもと思いつつ、じゃあどんなゴールにすればいいかはまだイメージ湧いてないので探ってきたい
    - [INVEST](https://ja.wikipedia.org/wiki/INVEST)という概念も、聞いて速攻で忘れてたので、色んな記事見て記憶を繋げてくの大事だなと思った
      - independent
      - negotiable
      - valuable
      - estimable
      - small
      - testable
- [技術書とお金の話 冬の夜](https://tech-book-cat.connpass.com/event/335843/)
    - 8月に開催したイベントの冬版の案内
    - すごくいいテーマだと思うので気になるけど、現地のみなので私は行けないなあ
      > 経済的にも精神的にも負担が少ない状態で、継続的に良い本を出し続けていくためには、技術書にまつわる「お金の話」をみんなでオープンにするのがいいのではないかと思っています
    - 私は家族に迷惑かけちゃって、2冊目を断念したクチです
- [クソコード動画「Userクラス」で考える技術的負債解消の観点](https://speakerdeck.com/minodriven/kusokododong-hua-userkurasu-dekao-eruji-shu-de-fu-zhai-jie-xiao-falseguan-dian)
    - システムは問題解決のために設計するものだけど、複数の問題解決を同じシステムでやろうとすると死ぬよってことっぽい
    - 膨大な具象パラメータの内、問題解決に必要な要素を抽出して簡略化する、要約に近い意味の抽象化・モデリングが大事とのこと
        - 統計・機械学習にも通じるやつーってなった
    - どうとでも解釈可能なガバガバな名前を用いると、関心の分離・分割統治の妨げになるよ
    - ↑を意識すると、物理的存在から複数のモデルが抽出されるよ
        - たとえば以下は現実世界のユーザーにひもづくけど、別個にモデリングできる
            - 個人アカウント
            - 法人アカウント
            - プロフィール
            - 支払い方法
    - モデリングはビジネスの深い理解がいるよ。興味がないなんて言ってられないよ
        - 病気の知識がない人は、悪魔にモデリングしちゃった
    - クソコードをなんとかしたかったら、問題を理解しろってことね、なるほ、そりゃそう

## ヨメナカタ

- [強いチームと開発生産性](https://speakerdeck.com/onk/2024-11-15-prefer-output-focused-development-team)
    - 「デュアルトラック」という言葉が出てきて、そういえば転職活動中に「デュアルトラックアジャイル」って言葉を聞いて気になってたんだと思いだした。しらべなきゃ
    - 読んでる間に0時になったのでギブアップ
- [Platform Engineeringことはじめ](https://www.youtube.com/watch?v=p-tXNHklVbw)
    - 1.5hの動画でヘビー……なのでそのうち……
    - SREむずいからSREの目標を達成する代替手段用意しようぜって気持ちはまあ分かるので、そのうち見たい
- [AIOpsとLLMOpsってどう違うの？？ ついでにLLMOpsに入門しよう！](https://speakerdeck.com/minorun365/aiopstollmopstutedouwei-uno-tuidenillmopsniru-men-siyou)
    - あとで……
- [Vim Keybindings Everywhere - The Ultimate List](https://github.com/erikw/vim-keybindings-everywhere-the-ultimate-list)
    - ちらみして、よう集めるなあ、すげーなあとなったが、Vimの外はVimじゃないからVimのマッピングじゃなくていいか……となるので優先度低
- [neivim/neovim feat(defaults): dot-repeat \[\<Space\> #31186\]](https://github.com/neovim/neovim/commit/cc6992f1ca443f4da01cb4d57159d4cef37b36b7#diff-bf1f7f26e5d4f1ecac3d75d02b5538eab7128605a09d30b534510084c332e293R4)
    - なんかドットリピートできないケースがあったらしい
    - `[<space>`はとくにマッピングされてない気がするけど、なんなんだろ……？
    - 優先度低いのでそのうち……

## ENJOY

アウトプットしながら読むと、いつもより繋がる……！感があっていいですね。続けたい。
後でじゃないけど、今週読んだ中で印象に残ったのは以下の記事でした。
人は易きに流れるし、失敗すると余計なのでロードマップを決めるべきじゃないと言い切って進んでるの凄いなあと関心するばかり。

> [ロードマップは決めきるべきじゃない。「売れない」から脱出するために、PdMがやるべきこと 【エムスリー山崎聡】](https://levtech.jp/media/article/interview/detail_523/)

先日読んだ[エムスリーテックブック7](https://techbookfest.org/product/g2gqKCQ96newVVkru0YgAm)の「第8章 エムスリー AI・機械学習チームはスクラムの夢を見るか?」とコアの価値観を共有しているように感じ、エムスリーの組織としての強むを感じた次第です。
