---
title: "vim-jpラジオ#24聞いた - OSS活動するVimmer"
author: atusy
date: '2024-12-23'
slug: vim-jp-radioa-24
categories: [Vim, vim-jp-radio]
tags: []
output:
  blogdown::html_page:
    md_extensions: +east_asian_line_breaks+task_lists
highlighhtjs: []
summary: |
  アカデミア系Vimmerの飽くなき挑戦を感じられる刺激的な回。
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = "#>", collapse = TRUE)
set.seed(123)
```

vim-jpラジオ、めっちゃおもろいけど、案外Xとかに感想流れてこないなと思って筆をとってみる。

2024-12-23公開の#24のゲストは#23に引き続きryoppippiさんとtaniさん。
今回は「OSS活動するVimmer」のテーマで、前回同様熱く・整然と語ってくれてました。

熱く・整然と語るって凄い技術よ、ほんとに。
\#23でも彼らは自分達が愛する世界を少しでも濃くリスナーの耳に届けようとして、淀みなく選びつくした言葉で語ってくれました。

これがアカデミア系Vimmerの実力……！と思われるかもしれませんが、たぶん、彼らが異常値。
じゃないと、そこまで語りのうまくない博士課程卒業系VimmerのAtusyが救われません。

パーソナリティのありすえさんも活発にOSS活動されていることもあり、三者三様な話を聞けたのは面白かったですね。
OSS活動の入口にvim-jpやdotfilesを挙げていたところは特に印象的。
OSS活動というと、つい誰かに使ってもらうためのものを自作したり、誰かが作ったものに貢献する話を切り口にしがちです。
しかし、その前段階として、vim-jpのようなコミュニティで話に花を咲かせて勢いづけたり、そもそも誰の役にたてるとか考えずにdotfilesから始めたりするというのは、面白い切り口だと思います。
特にdotfilesは、分からないことをvim-jpなどで人に聞いたり、うまくやってるところを誰かが参考にしてくれたりで、自分の外に花開いていく可能性もあるので、なるほどなあと思いました。
OSS活動を始めるにあたってGitやGitHubに慣れるという課題もあるので、dotfilesは技術的な意味でも良い入口だと思います。

パーソナリティもゲストもOSSのきっかけは違うところにあるのに、後々の体験から他の糸口を見つけてくるところ、すごい。
たぶん、これは彼らが日々刺激に貪欲だからなのかなあとも思いました。
実際、若い彼ら（30前？）が、若いうちに刺激を得ておけと語ってました。

他にも季節ならではの話やVim Conf、OSS活動を通じて得られた感謝など、もりだくさん！
聞き応えありです。

年明けも楽しみですね！
