---
title: "モノリポだっていけちゃうdenols/ts_ls共存術（Neovim >= 0.11）"
author: atusy
date: '2025-09-03'
slug: node-deno-decision-with-monorepo-support
categories: [Tech]
tags: [Neovim, LSP]
output:
  blogdown::html_page:
    md_extensions: +east_asian_line_breaks+task_lists
highlighhtjs: [Lua]
summary: |
    Neovim >= 0.11では言語サーバーを簡単に自動起動する方法として`vim.lsp.enable({ ... })`があるけど、FileTypeイベントに応じて`vim.lsp.start(...)`を呼べばもっと細かい制御ができるよ。応用すれば、denols/ts_lsの共存も細やか。モノリポだって怖くない。
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = "#>", collapse = TRUE)
set.seed(123)
options(digits.secs = 0)
```

[Vim駅伝](https://vim-jp.org/ekiden/)2025-09-03の記事です。
前回の記事はkawarimidollさんによる[Neovim 0.12（開発版）でcopilot-language-serverを設定してみたぞ（脱copilot.lua）](https://zenn.dev/vim_jp/articles/a6839f7204a611)でした。
私の直近の[記事](https://blog.atusy.net/2025/08/29/copilot-via-nvim-lsp-client/)を早速参考にしていただいて、うれしかったです。

さて、本題。

ランタイムが群雄割拠しているTypeScript/JavaScriptのプロジェクトにおいて、適切な言語サーバー選びは重要項目です。
Neovimでの設定方法について毎年のように記事が出ています。

* 2024
    * [俺の denols/tsserver(vtsls) 共存術 for Neovim 2024](https://zenn.dev/vim_jp/articles/10b408bc0cf077)
* 2023
    * [denols/typescript-lsのLSPスイッチングは意外と気を遣うよという話](https://zenn.dev/vim_jp/articles/69d26e3f7b0e35)
* 2022
    * [neovim lsp でdenolsとtsserverを自動で切り替える](https://zenn.dev/mochi/articles/e6b2735108157c)
* 2021
    * [https://zenn.dev/kawarimidoll/articles/2b57745045b225](https://zenn.dev/kawarimidoll/articles/2b57745045b225)

適切な言語サーバーをバッファにアタッチする方法として、2022年と2024年の記事では、両方をアタッチしてから不適切な方をデタッチしていました。
その背景には、[nvim-lspconfig](https://github.com/neovim/nvim-lspconfig)プラグインの仕様が関係していたかと思います。
このプラグインによる言語サーバーの自動起動機構にユーザー側でロジックを足すことが難しく、停止ロジックでごまかしていたと思います。

ところが、`vim.lsp.enable()`が実装されたNeovim >= 0.11で事情が変わり、[nvim-lspconfig](https://github.com/neovim/nvim-lspconfig)プラグインを使わずに本体と自身の設定で自動起動を制御するようになりました。
たとえば、`vim.lsp.enable("denols")`を設定に仕込んでおくと、`vim.lsp.config.denols.filetypes`にマッチするファイルタイプに対して自動的に`denols`がアタッチされます。

この、ユーザーに自動起動するか委ねる変化により、`ts_ls`を使うか`denols`を使うかも起動のタイミングで決めやすくなりました。
無駄にプロセスを起動することもないですし、バッファ単位で言語サーバーを選べるので、nodeとdenoが混在するモノリポなんてレアケースも怖くありません。

設定はざっくり以下の通りです。

```lua
-- 起動条件が単純な言語サーバーは `vim.lsp.enable` で自動起動させる
vim.lsp.enable({ "lua_ls", "pyright" })

-- 起動条件が複雑な言語サーバーはFileTypeイベント時に判定する
--（ts_ls/denols）
vim.api.nvim_create_autocmd("FileType", {
  group = vim.api.nvim_create_augroup("LspStartNodeOrDeno", { clear = true }),
  callback = function(ctx)
    if not vim.tbl_contains(
        { "javascript", "javascriptreact", "javascript.jsx", "typescript", "typescriptreact", "typescript.tsx" },
        ctx.match
    ) then
      return
    end

    -- node
    if vim.fn.findfile("package.json", ".;") ~= "" then
      vim.lsp.start(vim.lsp.config.ts_ls)
      return
    end

    -- deno
    vim.lsp.start(vim.lsp.config.denols)
  end,
})
```

Neovim >= 0.11向けのLSPの設定方法をまず知りたいという方は、kawarimidollさんの記事をご覧ください。

> [Neovim0.11用のLSP設定](https://zenn.dev/kawarimidoll/articles/b202e546bca344)

また、nodeかdenoかの判定に`package.json`の有無を使っていますが、もう少しこだわるならkyoh86さんの記事をご参考ください。

> [denols/typescript-lsのLSPスイッチングは意外と気を遣うよという話](https://zenn.dev/vim_jp/articles/69d26e3f7b0e35)

## ENJOY!!
