---
title: "EMってなんだろうと視野を広げにEngineering Managers Lounge 2025年9月いってきた"
author: atusy
date: '2025-09-26'
slug: em-lounge-202509
categories: [Essay]
tags: [Management]
output:
  blogdown::html_page:
    md_extensions: +east_asian_line_breaks+task_lists
highlighhtjs: [Lua]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = "#>", collapse = TRUE)
set.seed(123)
options(digits.secs = 0)
```

2025年9月に転職してEngineering Managerを名乗り始めたちょうどいいタイミングで、Engineering Managers Loungeに参加しました。
実はもっと前から参加したいとは思ってたので、このタイミングなのはたまたまです。

Engineering Managers Lougngeはソフトウェア開発に携わるマネージャーが、社外のマネージャーと対話をしたり、悩みを相談し合ったり、明日からまた元気に仕事をするための憩いの場を目指しているそうです。

> <https://emlounge.connpass.com/event/367237/>

自分の実現したいことにはエンジニアリングマネージャーが丁度いいポジションだなと思ってはいたものの、周りに同じ役割の人がいなかったので、視野を広げるために参加しました。

## よかったところ

* 明示的なEMに限らず「ソフトウェア開発に携わるマネージャー」が、EMってこんな役回りだよね、それに近しいところで頑張ったり悩んだりしてるんだよねって感じで集まってて、10人程度の小規模ながらに多様性がある
* 社外のマネージャー同士だからこそ話せることを話せる
* みんな技術大好きそうな割に技術の話にならなかったり、なっても一瞬で逸れてっておもろい
* みんなポジティブ
* みんな言語化も深掘りも上手だから議論が弾む
* 懇親会もディープに話せた

## イベント内容

この日は2部構成で、Lightening Talkの後に、リーンコーヒー形式でのフリーディスカッションという流れでした。

### Lightening Talk

Lightening TalkはEMのオンボーディング、1on1で使えるクリーンランゲージ、EM引き継ぎの成功談・失敗談の3本。

* 自分はEMに限らずマネジメント業でなにをどう進めるか手探りで開拓してて、体系的にオンボーディング受けたことないけど、体験入部制度まであるCybozuさんいいなー
* 自分の1on1は関係構築目的の雑談主体で、課題があれば傾聴・コーチングに切り替える形式。クリーンランゲージはもともとカウンセリング出身でバイアスを排して聞き出す技術みたいだけど、課題解決支援だけじゃなくて雑談での話の深掘りかたとしても参考になるなー
* まだEMを任命する立場になったことないけど、1件ごとの成功・失敗も組織の成長や個人のキャリアって観点では成功に繋がってってる感あっていいなー。とはいえ、EMの失敗って人への影響が大きいからケアが大変そうだなー

なんてこと思いながら聞いてました。

このLTが後のフリーディスカッションや、懇親会での話題になったりしてました。

### リーンコーヒー形式のフリーディスカッション

フリーディスカッションは、参加者が話したいテーマを出して、投票し、参加者が興味あるテーマのテーブルに集まって話すというリーンコーヒー形式でした。

得票数の高い順に3つの話題が併走するサイクルを3回繰り返しました。

#### 1周目: ローパフォーマーとの向き合い方

1周目は得票数の高い話題の中から1つを選ぶところがおもしろくて、どれも絶対に盛り上がるだろう中で、自分の興味に合わせるか？それとも普段なら自分が話さないテーマを選ぶか？という葛藤がありました。
私は視野を広げるという目標に沿って、普段なら自分が話さないテーマの「ローパフォーマーとの向き合い方」を選びました。
あと、センシティブで他でなかなか話せないよなという貴重さも選択を後押ししました。

ローパフォーマーってそもそもどんな人だろ……？と思ってたのですが、ジョブグレードや目標に対して期待される成果を出せていない人、という定義で話が進みました。
私は幸いなことに、あからさまなローパフォーマーと関わったことがないので、「期待にこたえれてないよ」と伝えるのめっちゃ辛そう……と思いながら、話に参加していました。

評価を伝えるという観点では、相手にやる気があるか・行動しているかが凄く重要で、これらが伴わないなら心を無にして対応するしかない印象でした。
時には人事などの第三者をたよるという選択肢を知れたのもよかったです。

一方、やる気があり行動もしていて、結果が伴わない人との向き合い方はなかなかに難しそうでした。
ただ、結果が伴わないなら、努力の方向性が間違っているか、結果を出しやすい環境にないかだろうなと思います。
継続的にローパフォーマンスならマネジメントの失敗として己と向き合うことになりそうです。
短期的なローパフォーマンスなら目標・環境を共に見直す、まさにマネージャーとしての腕の見せどころですね。

20分で話しきれなかったところとして、じゃあ頑張ってるローパフォーマーに評価を伝えるとき、どうするか……？みたいなところはありそうです。

あとはローパフォーマー評価が下るよりも前に兆候を見出して調整できると、マネージャーとして一流なのかなーと思ったりしました。

#### 2周目: EMの目標

2周目は「EMの目標」を選びました。
もう1つ気になった話題に「EMとSMはどう違う？」というのがありましたが、初見で自明に違うと思ったことや、他の人がEMの立場で見据える先の景色に興味があったので、「EMの目標」を選びました。

一方で「EMとSMはどう違う？」も得票数相応に人々の関心を寄せているわけで、自明じゃない部分もあるのでは……？と思い気になった部分でした。
こちらについては別の記事で語ろうと思います。

LTの中でうまくいってるチームは楽しそうという話があったのですが、じゃあ楽しく仕事できるチームを作ることがEMの目標なのかというと、楽しさは結果だという話が出て印象的でした。
楽しそうにしながら価値を提供しないチームもありえますからね。

私はそこで腑に落ちて止まっちゃったのですが、他の方の「プロダクトに魅力を感じている」という表現はいっそう的を得ていたと思います。

価値の有無によらず自らの行いに楽しさを感じることはあっても、価値を出さないと「プロダクトに魅力を感じている」状態にはならない。
価値を出していてもプロダクトに魅力を感じていないチームは疲弊する。

そう思うと、「プロダクトに魅力を感じながら楽しく価値提供に繋がる行動を続けられるチーム作り」がEMの目標なのだろうなと。

これまで楽しく価値を提供し続けるチームを作りたいと思っていたところに、一段と踏み込めてよかったです。

目標の別の視点としてEM自身が目標をどう設定し、どう評価されるか、みたいな話もでてましたが、こちらは割愛。

#### 3周目: EMをやるぞと決めたきっかけ

3周目にして私の出したお題がきました。

そもそもEMをする理由って私と他の方で同じなのかな、違うのかなという好奇心と、LTの中でEM候補を常に数人リスト化しとくという話に対してじゃあどんな人をリストしとくといいかなーという疑問とを、同時に扱える話題だと思っていました。

書き疲れてきたので「きっかけ」を省きつつ、EMをやる人がどんなタイプか見えてきたところをさっくりまとめます。

1. 組織の課題に対して愚痴るより解決したいと考えるタイプ
2. なんかの拍子に得た立場を楽しもうと思えるタイプ
3. 隙間を埋めることに喜びを感じるタイプ

なるほどなーとなりました。

# ENJOY!

2ヶ月に1度を目安にしてるとのことで次は11月かな？
めっちゃ楽しみにしてます！

運営の皆様、会場提供頂いたCybozuさん、ありがとうございました！


<!--

##### 気になった「EMとSMはどう違う？」

初見で置かれてる立場違うし自明に違うと思ったのですが、相応に得票してるからには何かあるのかな？と気になった次第です。
呼称や置かれる文脈の違いはあれど、業務内容としては相似で、評価の有無が主な違いという結論だったみたいです（<https://x.com/kawanotron/status/1971195576499994827>）。

個人的には「エンジニアリングマネージャーのロードマップ」で語られた、EMがなんとかする（マネージする）4つのPに沿って考えると違いが見えてくるかなと思います。

> * People Management
> * Platform Management
> * Product Management
> * Project Management
>
>  <https://hirokidaichi.github.io/presentation/emconf.html#15>

EMは4つのPのバランスを適宜調整することが求められそうです。
一方SMはPeople（チーム）とPlatform（スクラム）をなんとかすることが主な役割で残りのPはスクラムチーム全体でなんとかするのかなと。
評価の有無のこともあり、SMはEMの一部を切り出した役割なのかなと感じました。

多くの組織にはProduct ManagerやProject Managerといった肩書もあるわけで、これらとEMの違いは何？と聞かれてもやっぱりEMの方が扱う範囲が広いになるのかなと思います。

じゃあなんで広く扱うEMが出てきたのかというと、Team Topologyでいうストリームアラインドチームをなんとかする役割が必要になったからかなと思います。

> ストリームとは、ビジネスドメインや組織の能力に沿った仕事の継続的な流れのことだ

Team Topologyは「ストリームとは、ビジネスドメインや組織の能力に沿った仕事の継続的な流れ」と定義し、ストリームに沿ったチームは仕事の流れで価値提供するまでに他のチームへの仕事の引き継ぎが必要ないと語ります。
もちろん、ストリームアラインドチームが全ての仕事を完結できるわけではなく、他のチームと協力する必要があり、プラットフォームチームという4つのPの1つを担うチームも紹介されていますが、基本としてPlatform Managementもストリームの一部なのかなと。

ストリームアラインドチームなら滞りなく価値を提供できるというなら、なんと素敵なことかと思います。

一方で、チームは流れにかかわるものすべて、たとえば4つのPをなんとかする必要があり、そこに責任を持つのがEMなのかなと。

ちなみにEMは4つのPをなんとかするために自己組織化を目指すかどうかは決まってないと思います。

スクラムチームもストリームアライドチームの1つの形だと思いますが、スクラムガイドで自己組織化を目指すと語られている点に大きな違いがありそうです。
自己組織化するためには最低でもProductとProjectはチームでなんとかする必要があり、それを実現するメンバー（People）と環境（Platform）をなんとかするのがSMなのかなと。
先程はEMの方が扱う範囲が広いという表現をしましたが、EMの目指す方向性を限定することで集中可能な役割としてSMがあるのかなと思います。



-->




