---
title: ""
author: atusy
date: '2025-11-21'
slug: 
categories: [Essay]
tags: [Agile, Retrospective]
output:
  blogdown::html_page:
    md_extensions: +east_asian_line_breaks+task_lists
highlighhtjs: [Lua]
summary: |
---

ふりかえりでは目につく課題が取り沙汰されがちだ。

だからというのも変だが、私は成功体験に意識を向けることを大事にしている。

> 言語化され成功体験は再現性を生み出し、更によい成功を生むエナジーなのです \
> by [\[アジャイルジャパン2025\]あなたのアジャイルがうまくいかない10の理由～"Reboot"のための処方箋～][https://www.docswell.com/s/samuraiRed/5WMQYG-2025-11-13-205802]

この表現が実に的を得ていると思う。

更によい成功を続けた先には目標達成が待っている。
「我々はなぜここにいるのか」を体現してくれる。
そこへ至るエナジーはあればあるほど良い。

だから成功体験が大事なのだ。

ところで成功体験はKPTでいうところのKeep（続けたいこと）だ。

KPTはKeep（続けたいこと）、Problem（課題）に対してTry（改善案）を考えるフレームワークだ。

Problem（課題）は「治したい」にせよ「伸ばしたい」にせよ、変化を指向する。Tryを考えやすい。

おかげで、チームとして取り決めての解決が必要なことか、深く考えずに飛び付きたくなる。
我々は問題だらけだとか、ろくな成功がないだとか、そんな気分になってしまう。

だから、深く考える前にKeep（続けたいこと）に目を向けたい。

* ただ今まで通り続けばいいのか？
* そもそも再現可能か？
* 伸びしろはあるか？

前向きな話なのでエナジーになるし、これらの問い掛けはKeep発のTryの種にもなる。

深堀るためには発掘も欠かせまい。
ここらはファシリテーターに限らず慣れてる人の腕の見せ所だ。

* しょうもない成功も拾い上げて、ハードルをさげる
* Problem（課題）まみれになったらその周辺に成功がなかったか話をふる
    * 課題発見能力の高さや、初動の速さなど、さまざまなKeep（続けたいこと）要素があるはずだ
* KeepかProblemか迷うくらいならKeepに書くよう促す

課題発見が能力であるように、成功発見も能力だ。伸ばせる。

課題解決は、しばしば「どうありたいか」より「どうしたくないか」に引きずられがちだ。

成功体験に目を向けて、チームの「どうありたいか」を引き出し、更によい成功を生むだけでなく、課題解決とのシナジーを生みたいなと思う。

そうすれば、途方のない目標達成にも近付く実感を得られると思うのだ。
